/* Dữ liệu tra cứu pha thuốc BVTV
 * Tổng hợp từ CropLife Technical Monograph No. 2, WALES (Syngenta/Virginia Tech),
 * danh mục thuốc BVTV Việt Nam, nhãn/tài liệu kỹ thuật nhà sản xuất.
 * Luôn ưu tiên nhãn trên bao bì khi có khác biệt.
 */
window.BVTV = (function () {
  const FORMS = [
    {
      code: "WP",
      name: "Bột thấm nước",
      en: "Wettable Powder",
      vn: "BTN / BHN",
      group: "solid",
      mixStep: 1,
      color: "#7c5c2a",
      look: "Bột mịn, dễ bụi. Hòa nước tạo huyền phù đục, dễ lắng.",
      how: "Hòa thành hồ đặc trong ca nhỏ với ít nước sạch, khuấy kỹ cho hết vón. Đổ vào bình đã có 1/2–2/3 nước. Khuấy liên tục vì bột không tan hoàn toàn.",
      tips: [
        "Cần nhiều thời gian phân tán nhất — luôn cho vào trước các dạng lỏng.",
        "Đeo khẩu trang khi đổ bột, tránh hít bụi.",
        "Phun xong rửa béc kỹ; lưới lọc không nên nhỏ hơn 50 mesh.",
      ],
      avoid: "Không đổ bột khô trực tiếp vào EC/OD. Không pha khi nước phèn, nước cứng cao nếu chưa thử cốc.",
    },
    {
      code: "SP",
      name: "Bột tan trong nước",
      en: "Water Soluble Powder",
      vn: "BT",
      group: "solid",
      mixStep: 2,
      color: "#3d6b4f",
      look: "Bột; khi hòa đúng sẽ thành dung dịch trong hoặc hơi đục.",
      how: "Rắc từ từ vào nước đang khuấy. Đợi tan hết trước khi thêm thuốc khác.",
      tips: ["Tan thật sự trong nước, ít lắng hơn WP.", "Vẫn hòa riêng rồi mới đổ vào bình."],
      avoid: "Không trộn bột khô với thuốc đậm đặc.",
    },
    {
      code: "WG",
      name: "Hạt phân tán trong nước",
      en: "Water Dispersible Granule (WDG / DF)",
      vn: "HHN",
      group: "solid",
      mixStep: 3,
      color: "#8a6d3b",
      look: "Cốm/hạt nhỏ, ít bụi hơn WP. Nở và phân tán khi gặp nước.",
      how: "Rắc từ từ vào nước đang khuấy, đợi hạt tan hết (1–3 phút) rồi mới thêm thuốc khác.",
      tips: [
        "An toàn hơn WP vì ít bụi.",
        "Cho sau WP nếu pha chung hai dạng bột.",
        "Một số tài liệu quốc tế (WALES) cho WG ngay sau WP.",
      ],
      avoid: "Không đổ hạt vào dung dịch đã có nhiều dầu EC — hạt khó nở.",
    },
    {
      code: "SG",
      name: "Hạt tan trong nước",
      en: "Water Soluble Granule",
      vn: "HT",
      group: "solid",
      mixStep: 3,
      color: "#4a7c59",
      look: "Hạt tan hoàn toàn thành dung dịch.",
      how: "Cho vào nước đang khuấy, đợi tan hết.",
      tips: ["Khác GR/G/H: SG dùng để phun; GR/G/H là hạt rải gốc — không hòa nước phun."],
      avoid: "Không nhầm với thuốc hạt rải (GR, G, H).",
    },
    {
      code: "SC",
      name: "Huyền phù đậm đặc",
      en: "Suspension Concentrate (Flowable)",
      vn: "HF",
      group: "liquid-water",
      mixStep: 4,
      color: "#1d4e89",
      look: "Sệt, đục. Hoạt chất rắn lơ lửng trong nước.",
      how: "Lắc chai thật kỹ trước khi rót. Cho vào bình sau khi dạng bột đã phân tán đều.",
      tips: ["Dễ lắng trong chai — lắc là bắt buộc.", "Khuấy lại khi phun gián đoạn."],
      avoid: "Không đổ SC đặc vào EC chưa pha loãng.",
    },
    {
      code: "CS",
      name: "Huyền phù vi nang",
      en: "Capsule Suspension",
      vn: "Vi nang",
      group: "liquid-water",
      mixStep: 5,
      color: "#2563a8",
      look: "Huyền phù; hoạt chất bọc nang, nhả chậm.",
      how: "Lắc đều. Cho sau SC thông thường theo một số hướng dẫn tank-mix.",
      tips: ["Giữ hiệu lực kéo dài.", "Không nghiền/phá nang bằng cách khuấy quá mạnh không cần thiết."],
      avoid: "Một số CS kỵ dung môi mạnh của EC — thử cốc trước.",
    },
    {
      code: "OD",
      name: "Huyền phù trong dầu",
      en: "Oil Dispersion",
      vn: "Dầu phân tán",
      group: "liquid-oil",
      mixStep: 6,
      color: "#b45309",
      look: "Sệt, gốc dầu. Bám lá tốt, dễ gây váng nếu pha sai thứ tự.",
      how: "Lắc chai. Cho sau SC, trước EC. Khuấy đều ngay.",
      tips: ["Benevia 100OD thuộc dạng này.", "Nhạy với nước bẩn và pha vội."],
      avoid: "Không đổ OD vào bột chưa tan. Tránh nắng gắt — dầu dễ cháy lá.",
    },
    {
      code: "EC",
      name: "Nhũ dầu đậm đặc",
      en: "Emulsifiable Concentrate",
      vn: "ND / thuốc sữa",
      group: "liquid-oil",
      mixStep: 7,
      color: "#c2410c",
      look: "Lỏng, thường có mùi dung môi. Pha nước thành sữa đục.",
      how: "Cho gần cuối nhóm thuốc, sau khi mọi dạng rắn và SC đã phân tán. Khuấy tạo nhũ ổn định.",
      tips: [
        "Loang trải, bám dính tốt, chịu mưa hơn nhiều dạng khác.",
        "Tăng liều + nắng nóng = rủi ro cháy lá cao.",
        "Hai loại EC trong một bình dễ quá tải dung môi — hạn chế.",
      ],
      avoid: "Không cho EC vào trước WP/WG. Không pha với nước phèn.",
    },
    {
      code: "EW",
      name: "Nhũ tương dầu trong nước",
      en: "Emulsion, oil-in-water",
      vn: "Nhũ tương",
      group: "liquid-oil",
      mixStep: 7,
      color: "#d97706",
      look: "Sữa, ít mùi dung môi hơn EC.",
      how: "Cho cùng bước với EC, sau SC/OD.",
      tips: ["Mềm hơn EC với cây trồng."],
      avoid: "Vẫn thử cốc khi phối nhiều loại.",
    },
    {
      code: "ME",
      name: "Vi nhũ",
      en: "Micro-emulsion",
      vn: "Vi nhũ",
      group: "liquid-oil",
      mixStep: 7,
      color: "#ca8a04",
      look: "Trong đến hơi đục; hạt nhũ rất nhỏ.",
      how: "Cho cùng nhóm EC/EW.",
      tips: ["Ổn định hơn EC thông thường."],
      avoid: "",
    },
    {
      code: "SL",
      name: "Dung dịch tan trong nước",
      en: "Soluble Concentrate / Soluble Liquid",
      vn: "DD",
      group: "liquid-water",
      mixStep: 8,
      color: "#0f766e",
      look: "Lỏng trong hoặc hơi opalescent. Tan thành dung dịch thật.",
      how: "Cho sau EC theo WALES. Hòa dễ, ít cần thời gian khuấy.",
      tips: ["Một số hướng dẫn VN xếp SL cùng EC ở bước cuối nhóm thuốc."],
      avoid: "",
    },
    {
      code: "SE",
      name: "Huyền phù-nhũ tương",
      en: "Suspo-emulsion",
      vn: "SE",
      group: "liquid-water",
      mixStep: 5,
      color: "#1e40af",
      look: "Vừa hạt rắn vừa giọt dầu trong nước.",
      how: "Lắc kỹ. Cho sau SC, trước EC.",
      tips: ["Khuấy liên tục khi phun."],
      avoid: "",
    },
    {
      code: "GR",
      name: "Hạt rải gốc",
      en: "Granule",
      vn: "G / H",
      group: "not-spray",
      mixStep: 0,
      color: "#57534e",
      look: "Hạt rắn dùng rải đất, không pha nước phun.",
      how: "Rải theo hàng/gốc theo nhãn. Không hòa vào bình phun.",
      tips: ["Ký hiệu GR, G, H trên nhãn Việt Nam thường là hạt rải."],
      avoid: "Không pha vào bình phun lá.",
    },
    {
      code: "ULV",
      name: "Phun lượng cực nhỏ",
      en: "Ultra Low Volume",
      vn: "ULV",
      group: "special",
      mixStep: 0,
      color: "#44403c",
      look: "Đậm đặc, dùng máy ULV, ít hoặc không pha nước.",
      how: "Theo máy và nhãn. Không dùng như thuốc pha bình đeo vai.",
      tips: [],
      avoid: "Không đổ ULV vào bình phun nước thông thường trừ khi nhãn cho phép.",
    },
    {
      code: "FS",
      name: "Huyền phù xử lý hạt",
      en: "Flowable concentrate for seed treatment",
      vn: "Xử lý hạt",
      group: "special",
      mixStep: 0,
      color: "#57534e",
      look: "Dùng trộn hạt giống, không phun lá.",
      how: "Trộn hạt theo nhãn.",
      tips: [],
      avoid: "Không dùng để phun cây.",
    },
    {
      code: "DP",
      name: "Bột rắc",
      en: "Dustable powder",
      vn: "Bột rắc",
      group: "not-spray",
      mixStep: 0,
      color: "#78716c",
      look: "Bột khô rắc trực tiếp, không hòa nước.",
      how: "Rắc theo nhãn.",
      tips: [],
      avoid: "Không pha bình phun.",
    },
  ];

  const MIX_ORDER = [
    {
      step: 0,
      title: "Nước sạch",
      detail: "Đổ 1/2 đến 2/3 bình. Bật khuấy (hoặc khuấy tay liên tục). Nước phèn, nước ao, nước cứng cao làm hỏng nhiều loại thuốc — đặc biệt sinh học và EC.",
      codes: [],
    },
    {
      step: 1,
      title: "Bột thấm nước — WP",
      detail: "Hòa hồ đặc riêng, đổ vào, khuấy đến khi không còn vón. Đây là bước khó tan nhất.",
      codes: ["WP"],
    },
    {
      step: 2,
      title: "Bột tan — SP",
      detail: "Cho vào khi WP đã phân tán. Đợi tan hết.",
      codes: ["SP"],
    },
    {
      step: 3,
      title: "Hạt phân tán / hạt tan — WG, SG",
      detail: "Rắc từ từ. Đợi hạt nở và phân tán 1–3 phút.",
      codes: ["WG", "SG"],
    },
    {
      step: 4,
      title: "Huyền phù nước — SC, CS, SE",
      detail: "Lắc chai. Cho từng loại, khuấy đều giữa mỗi lần.",
      codes: ["SC", "CS", "SE"],
    },
    {
      step: 5,
      title: "Dạng dầu — OD",
      detail: "Cho sau mọi dạng nước. Khuấy tạo hỗn hợp đồng nhất.",
      codes: ["OD"],
    },
    {
      step: 6,
      title: "Nhũ dầu — EC, EW, ME",
      detail: "Cho gần cuối nhóm thuốc. Tạo sữa đục ổn định.",
      codes: ["EC", "EW", "ME"],
    },
    {
      step: 7,
      title: "Dung dịch — SL",
      detail: "Theo WALES, SL vào sau EC. Hòa nhanh.",
      codes: ["SL"],
    },
    {
      step: 8,
      title: "Phân bón lá / vi lượng",
      detail: "Hòa riêng, liều thấp, cho sau thuốc. Không dùng khi cây đang bệnh nặng (đạm làm bệnh lan).",
      codes: [],
    },
    {
      step: 9,
      title: "Chất bám dính / trải",
      detail: "Cho cuối cùng. Châm nước đủ bình, khuấy, phun ngay. Không để qua đêm.",
      codes: [],
    },
  ];

  const PRODUCTS = [
    {
      id: "dipel",
      name: "Dipel 6.4WG",
      form: "WG",
      kind: "tru-sau",
      bio: true,
      ai: "Bacillus thuringiensis var. kurstaki 64 g/kg (32.000 IU/mg)",
      group: "IRAC 11A",
      company: "Sumitomo",
      targets: "Sâu tơ, sâu cuốn lá, sâu ăn lá tuổi 1–2 (sâu phải ăn phải thuốc).",
      crops: "Cải bắp, chè và rau ăn lá theo nhãn.",
      dose: {
        per16: "20–40 g",
        note: "Nhãn: 0,5–1,0 kg/ha (cải bắp, 400 lít nước/ha) ≈ 20–40 g/bình 16 lít. Chè: 10 g/8 lít.",
      },
      phi: "Không khuyến cáo ngày trên một số đăng ký; đọc nhãn lô hàng.",
      mixNotes: [
        "Sinh học: pH nước nên 4,5–8. Nước kiềm làm giảm hiệu lực.",
        "Có thể phối nhiều thuốc hóa học nếu thử cốc đạt; phun trong ngày.",
        "Đồng: một số tài liệu Dipel cho phép phối nhưng phải phun ngay. Booc-đô, vôi lưu huỳnh: không phối.",
        "Một số nhãn Dipel cũ cấm phối chlorothalonil (Daconil) — ưu tiên không pha chung.",
      ],
      tags: ["sinh học", "Bt", "sâu ăn lá"],
    },
    {
      id: "secure",
      name: "SECURE 10EC",
      form: "EC",
      kind: "tru-sau",
      bio: false,
      ai: "Chlorfenapyr 100 g/l",
      group: "IRAC 13",
      company: "Hợp Trí / phổ biến trên thị trường VN",
      targets: "Sâu cuốn lá, bọ trĩ, nhện đỏ, sâu xanh da láng; hữu ích khi sâu đã kháng cúc, lân, carbamate.",
      crops: "Lúa, dưa hấu, cây có múi, đậu theo nhãn.",
      dose: {
        per16: "15–40 ml",
        note: "Khoảng phổ biến trên hướng dẫn phân phối: 15–40 ml/bình 16 lít. Chọn theo đối tượng trên nhãn.",
      },
      phi: "Theo nhãn lô hàng.",
      mixNotes: [
        "Dạng EC: cho vào bình gần cuối, sau WP/WG/SC.",
        "Hạn chế pha chung với EC khác (Neem, Permethrin, Mospilan) vì tăng dung môi, dễ cháy lá.",
        "Không tăng liều khi nắng gắt.",
      ],
      tags: ["nhũ dầu", "sâu kháng"],
    },
    {
      id: "prevathon",
      name: "Dupont Prevathon 5SC",
      form: "SC",
      kind: "tru-sau",
      bio: false,
      ai: "Chlorantraniliprole 50 g/l (5%)",
      group: "IRAC 28",
      company: "FMC (trước đây DuPont)",
      targets: "Sâu cuốn lá, sâu đục thân, sâu tơ, bọ nhảy, dòi đục lá, sâu xanh — sâu ngừng ăn nhanh.",
      crops: "Lúa, bắp cải, cà chua, dưa hấu, đậu, hành theo nhãn.",
      dose: {
        per16: "15 ml",
        note: "Hướng dẫn phổ biến: 15 ml/bình 16 lít hoặc 25 ml/bình 25 lít. Không phun quá 2 lần/vụ trên một số cây.",
      },
      phi: "1–3 ngày tùy cây (cà chua/dưa 1 ngày; lúa/bắp cải khoảng 3 ngày — đối chiếu nhãn).",
      mixNotes: [
        "Lắc gói/chai trước khi rót.",
        "Không pha chung Benevia 100OD: cùng nhóm IRAC 28, lãng phí và tăng nguy cơ kháng.",
        "Cho vào sau dạng bột, trước EC/OD.",
      ],
      tags: ["diamide", "lưu dẫn cục bộ"],
    },
    {
      id: "benevia",
      name: "BENEVIA 100OD",
      form: "OD",
      kind: "tru-sau",
      bio: false,
      ai: "Cyantraniliprole 100 g/l",
      group: "IRAC 28",
      company: "FMC",
      targets: "Bọ trĩ, bọ phấn, dòi đục lá, sâu xanh, rầy — phổ rộng hơn Prevathon về chích hút.",
      crops: "Cà chua, dưa hấu, dưa chuột, ớt, lúa, xoài theo nhãn.",
      dose: {
        per16: "20–25 ml",
        note: "Nhãn: khoảng 0,3–1,0 lít/ha tùy cây. Thực tế phổ biến 25 ml/20 lít trên rau. Quy về 16 lít ≈ 20 ml — luôn theo nhãn cây trồng.",
      },
      phi: "Theo nhãn.",
      mixNotes: [
        "Dạng OD: cho sau SC, trước hoặc thay bước EC.",
        "Không pha với Prevathon (cùng IRAC 28).",
        "Lắc kỹ. Tránh nắng gắt vì gốc dầu.",
      ],
      tags: ["diamide", "bọ trĩ", "dầu"],
    },
    {
      id: "permethrin",
      name: "Map-Permethrin 50EC",
      form: "EC",
      kind: "tru-sau",
      bio: false,
      ai: "Permethrin 500 g/l",
      group: "IRAC 3A",
      company: "Map Pacific",
      targets: "Sâu cuốn lá, sâu xanh da láng, sâu đục quả, rệp sáp, bọ xít muỗi — tiếp xúc, phổ rộng.",
      crops: "Lúa, lạc, đậu nành, cà phê, điều theo nhãn Map.",
      dose: {
        per16: "10–16 ml",
        note: "Lúa sâu cuốn lá: 15 ml/bình 25 lít ≈ 10 ml/16 lít. Lạc: 25 ml/25 lít. Cà phê rệp sáp: 0,06–0,09% (9,6–14,4 ml/16 lít).",
      },
      phi: "Theo nhãn.",
      mixNotes: [
        "Cúc tổng hợp: độc với ong, cá, thiên địch — không phun khi hoa nở rộ.",
        "Hạn chế pha 2 EC. Cho vào cuối nhóm thuốc.",
      ],
      tags: ["cúc tổng hợp", "tiếp xúc"],
    },
    {
      id: "mospilan",
      name: "Mospilan 3EC",
      form: "EC",
      kind: "tru-sau",
      bio: false,
      ai: "Acetamiprid 3% w/w",
      group: "IRAC 4A",
      company: "Summit / Ishihara",
      targets: "Rầy nâu, rầy lưng trắng, rầy xanh, rệp sáp, bọ trĩ — tiếp xúc, vị độc, lưu dẫn.",
      crops: "Lúa, cà phê, hồ tiêu, vừng, bông vải theo nhãn.",
      dose: {
        per16: "20–36 ml",
        note: "Hướng dẫn phổ biến 30–56 ml/bình 25 lít. Liều ha thay đổi mạnh theo cây (hồ tiêu 0,08%; lúa theo nhãn lít/ha). Đọc nhãn cây đang trồng.",
      },
      phi: "7 ngày (nhiều cây); lúa có thể 14 ngày — đối chiếu nhãn.",
      mixNotes: [
        "Cùng nhóm 4A với Map Jono (imidacloprid) và Thiamax (thiamethoxam) — không pha chung, không luân phiên sát nhau.",
        "Dạng EC: bước nhũ dầu.",
      ],
      tags: ["neonicotinoid", "rầy", "rệp"],
    },
    {
      id: "jono",
      name: "MAP JONO 700WP",
      form: "WP",
      kind: "tru-sau",
      bio: false,
      ai: "Imidacloprid 700 g/kg",
      group: "IRAC 4A",
      company: "Map Pacific",
      targets: "Rầy nâu, rầy xanh, sâu xám — hàm lượng cao nên liều gam rất nhỏ.",
      crops: "Lúa, ngô, bông vải theo nhãn Map.",
      dose: {
        per16: "1,6 g",
        note: "Nhãn Map: 40 g/ha, 400 lít nước/ha; hoặc 20 g/phuy 200 lít. Bình 16 lít ≈ 1,6 g. Dùng cân/gói định lượng, không ước chừng.",
      },
      phi: "Theo nhãn.",
      mixNotes: [
        "WP: hòa hồ đặc trước, cho vào bình đầu tiên trong các thuốc.",
        "Không pha với Mospilan hoặc Thiamax (cùng IRAC 4A).",
      ],
      tags: ["neonicotinoid", "rầy", "bột"],
    },
    {
      id: "amistar",
      name: "Amistar 250SC",
      form: "SC",
      kind: "tru-benh",
      bio: false,
      ai: "Azoxystrobin 250 g/l",
      group: "FRAC 11",
      company: "Syngenta",
      targets: "Thán thư, mốc sương, đốm lá, thối quả, sương mai — nội hấp, phổ rộng. Dễ kháng: không lạm dụng.",
      crops: "Cam, xoài, cà chua, dưa hấu, ớt, thanh long, chuối theo nhãn.",
      dose: {
        per16: "8–16 ml",
        note: "Nhiều đăng ký 0,4–0,5 lít/ha hoặc 0,08%. Với 400–500 lít/ha ≈ 8–16 ml/16 lít. Một số hướng dẫn thực tế cao hơn — bám nhãn cây.",
      },
      phi: "Theo nhãn cây trồng.",
      mixNotes: [
        "Lắc chai. Cho bước SC.",
        "Nên phối hoặc luân phiên với thuốc đa vị trí (Daconil, đồng) để chống kháng strobilurin.",
        "Không thay thế thuốc trị khi bệnh đã nặng trên một số đối tượng — chủ yếu phòng và chớm bệnh.",
      ],
      tags: ["strobilurin", "nội hấp"],
    },
    {
      id: "ranman",
      name: "Ranman 10SC",
      form: "SC",
      kind: "tru-benh",
      bio: false,
      ai: "Cyazofamid 100 g/l",
      group: "FRAC 21",
      company: "Nichino / Sumitomo (đăng ký VN)",
      targets: "Sương mai, giả sương mai (Oomycete) trên nho, cà chua, dưa.",
      crops: "Nho, cà chua, dưa leo, dưa hấu, khoai môn theo nhãn.",
      dose: {
        per16: "15–20 ml",
        note: "Nhãn: 0,8–1,0 lít/ha / 400–500 lít nước. Thực tế phổ biến 15–20 ml/bình 16 lít.",
      },
      phi: "Khoảng 7 ngày trên nhiều hướng dẫn phân phối.",
      mixNotes: [
        "Lắc kỹ. Bước SC.",
        "Đặc trị oomycete — không thay thế thuốc thán thư/phấn trắng do nấm thật.",
        "Có thể cân nhắc luân phiên với dimethomorph (Insuran/Phytocide) vì khác FRAC.",
      ],
      tags: ["oomycete", "sương mai"],
    },
    {
      id: "metaxyl",
      name: "METAXYL 25WP",
      form: "WP",
      kind: "tru-benh",
      bio: false,
      ai: "Metalaxyl 25%",
      group: "FRAC 4",
      company: "Nhiều nhà (cùng hoạt chất)",
      targets: "Sương mai, mốc sương, lở cổ rễ, thối gốc do Phytophthora/Pythium — lưu dẫn. Dễ kháng.",
      crops: "Rau, hồ tiêu, sắn, cà chua, khoai tây theo nhãn lô.",
      dose: {
        per16: "20 g",
        note: "Một hướng dẫn: 10 g/bình 8 lít → 20 g/16 lít. Luôn đối chiếu nhãn sản phẩm đang cầm.",
      },
      phi: "Khoảng 7 ngày trên một số nhãn.",
      mixNotes: [
        "Nên phối với thuốc tiếp xúc (Daconil, mancozeb, đồng dạng phù hợp) vì metalaxyl đơn độc dễ mất hiệu lực do kháng.",
        "Hòa WP trước. Một số tài liệu cho phép phối COC — vẫn thử cốc; COC 85 khuyến cáo phun riêng.",
      ],
      tags: ["phenylamide", "Phytophthora"],
    },
    {
      id: "insuran",
      name: "INSURAN 50WP",
      form: "WP",
      kind: "tru-benh",
      bio: false,
      ai: "Dimethomorph 50% (500 g/kg)",
      group: "FRAC 40",
      company: "Phổ biến trên thị trường VN",
      targets: "Chết nhanh tiêu, mốc sương, giả sương mai, xì mủ, thối quả — nội hấp.",
      crops: "Tiêu, cà chua, dưa, vải, sầu riêng, cao su theo nhãn.",
      dose: {
        per16: "15 g",
        note: "Cùng nhóm liều với Phytocide: khoảng 0,3–0,4 kg/ha ≈ gói 15 g/bình 16 lít trên một số hướng dẫn.",
      },
      phi: "Theo nhãn.",
      mixNotes: [
        "Không pha với Phytocide hoặc Eddy: trùng dimethomorph (FRAC 40).",
        "WP: hòa trước. Thường phối thuốc tiếp xúc khác nhóm.",
      ],
      tags: ["CAA", "Phytophthora"],
    },
    {
      id: "phytocide",
      name: "Phytocide 50WP",
      form: "WP",
      kind: "tru-benh",
      bio: false,
      ai: "Dimethomorph 500 g/kg",
      group: "FRAC 40",
      company: "Phổ biến trên thị trường VN",
      targets: "Sương mai, chết nhanh tiêu, giả sương mai, loét sọc mặt cạo.",
      crops: "Cà chua, tiêu, dưa hấu, vải, cao su theo nhãn.",
      dose: {
        per16: "15 g",
        note: "Hướng dẫn: 0,3–0,4 kg/ha; gói 15 g/bình 16 lít trên cà chua (một nguồn phân phối).",
      },
      phi: "Theo nhãn.",
      mixNotes: [
        "Không pha Insuran hoặc Eddy (cùng dimethomorph).",
        "Một hướng dẫn gợi ý phối Norshield (đồng hydroxide) — khác COC 85. COC 85 vẫn nên phun riêng.",
      ],
      tags: ["CAA", "Phytophthora"],
    },
    {
      id: "eddy",
      name: "EDDY 72WP",
      form: "WP",
      kind: "tru-benh",
      bio: false,
      ai: "Cuprous oxide 60% + Dimethomorph 12%",
      group: "FRAC M01 + 40",
      company: "Hợp Trí Summit",
      targets: "Phytophthora: chết nhanh, thối quả, mốc sương, vàng lá thối rễ — kép đồng + lưu dẫn.",
      crops: "Tiêu, sầu riêng, ca cao, cà phê, khoai tây theo nhãn.",
      dose: {
        per16: "40 g",
        note: "Tưới gốc tiêu: 500–600 g/200 lít (phòng/trị). Phun lá quy về bình 16 lít ≈ 40–48 g nếu dùng 500–600 g/200 lít. Ưu tiên theo mục đích phun hay tưới trên nhãn.",
      },
      phi: "Theo nhãn.",
      mixNotes: [
        "Đã chứa đồng + dimethomorph: không pha thêm COC 85, Insuran, Phytocide.",
        "Gốc đồng: hạn chế phối kháng sinh, fosetyl-Al, phân bón lá.",
        "WP: hòa kỹ, khuấy liên tục.",
      ],
      tags: ["đồng", "Phytophthora", "kép"],
    },
    {
      id: "kimono",
      name: "KIMONO APC 50WG",
      form: "WG",
      kind: "tru-benh",
      bio: false,
      ai: "Boscalid 50% w/w",
      group: "FRAC 7",
      company: "Đăng ký 6938/CNĐKT-BVTV",
      targets: "Sương mai và bệnh do nấm (SDHI). Dễ kháng — luân phiên nhóm khác.",
      crops: "Đậu tương (đăng ký sương mai) và cây khác theo nhãn lô.",
      dose: {
        per16: "21–26 g",
        note: "Nhãn đậu tương: 0,8 kg/ha, 500–600 lít nước/ha → khoảng 21–26 g/bình 16 lít.",
      },
      phi: "7 ngày (đậu tương trên nguồn danh mục).",
      mixNotes: [
        "WG: rắc vào nước đang khuấy, đợi nở hết.",
        "Khác nhóm với Amistar (11), Daconil (M05), Ranman (21) — phù hợp luân phiên.",
      ],
      tags: ["SDHI", "boscalid"],
    },
    {
      id: "coc",
      name: "COC 85WP",
      form: "WP",
      kind: "tru-benh",
      bio: false,
      ai: "Copper oxychloride 85% (tương đương Cu hữu hiệu theo nhãn)",
      group: "FRAC M01",
      company: "Nhiều nhà (COC 85 là tên hoạt chất/dạng phổ biến)",
      targets: "Thán thư, sẹo, vi khuẩn, phòng bệnh phổ rộng — tiếp xúc, rửa trôi nếu mưa.",
      crops: "Điều, cây ăn trái, rau theo từng sản phẩm đăng ký.",
      dose: {
        per16: "48 g (0,3%)",
        note: "Một đăng ký BM Super COC: 0,3%. 0,3% = 3 g/lít = 48 g/16 lít. Nguồn khác dùng thấp hơn — theo nhãn.",
      },
      phi: "Theo nhãn.",
      mixNotes: [
        "Khuyến cáo kỹ thuật VN: CuSO4, COC 85 và Booc-đô chỉ nên phun riêng — khác các đồng hydroxide (Kocide, Champion) có thể phối một số hoạt chất.",
        "Không phối kháng sinh BVTV, fosetyl-Al, phân bón lá.",
        "Kiềm: có thể làm giảm Bt (Dipel) nếu không phun ngay; Acti No Vate (vi sinh) không phối.",
      ],
      tags: ["đồng", "tiếp xúc", "phun riêng"],
    },
    {
      id: "daconil",
      name: "Daconil 500SC",
      form: "SC",
      kind: "tru-benh",
      bio: false,
      ai: "Chlorothalonil 500 g/l",
      group: "FRAC M05",
      company: "Nhiều thị trường; phổ rộng đa vị trí",
      targets: "Mốc sương, thán thư, đốm lá, đạo ôn, phấn trắng — tiếp xúc, bám mưa, ít kháng.",
      crops: "Cà chua, khoai tây, dưa, lạc, xoài, lúa, hoa hồng theo nhãn.",
      dose: {
        per16: "16–24 ml",
        note: "Hướng dẫn phổ biến 10–15 ml / 10–12 lít ≈ 13–24 ml/16 lít. Phun ướt đều hai mặt lá.",
      },
      phi: "Theo nhãn.",
      mixNotes: [
        "Lắc chai. Bước SC. Thuốc đa vị trí — nên dùng trong chương trình chống kháng strobilurin/SDHI.",
        "Một số nhãn Dipel cấm phối chlorothalonil — không pha Dipel + Daconil.",
        "Không phải thuốc trị Phytophthora lưu dẫn.",
      ],
      tags: ["đa vị trí", "tiếp xúc"],
    },
    {
      id: "neem",
      name: "Neem Nim 0.3EC",
      form: "EC",
      kind: "tru-sau",
      bio: true,
      ai: "Azadirachtin 0,3% (chiết xuất neem)",
      group: "IRAC UN (botanical) / chống ăn, IGR",
      company: "Thảo mộc — đối chiếu nhãn lô",
      targets: "Sâu tơ, rệp, bọ trĩ, ruồi đục lá — chủ yếu ức chế ăn và lột xác, không diệt tức thì.",
      crops: "Rau, cây ăn trái theo nhãn.",
      dose: {
        per16: "30–50 ml",
        note: "Khoảng thực tế phổ biến với azadirachtin 0,3% EC. Lắc đều. Phun sớm, lặp lại.",
      },
      phi: "Thường ngắn (khoảng 3–7 ngày) — theo nhãn.",
      mixNotes: [
        "EC thảo mộc: hạn chế pha thêm EC hóa học (Secure, Permethrin, Mospilan) — dễ cháy lá.",
        "Không phối chất kiềm (Booc-đô, vôi). Nắng gắt + dầu = cháy lá.",
        "Hiệu lực chậm: không kỳ vọng thay thuốc độc thần kinh khi mật độ sâu đã rất cao.",
      ],
      tags: ["thảo mộc", "neem", "rau an toàn"],
    },
    {
      id: "acti",
      name: "Acti No Vate 1SP",
      form: "SP",
      kind: "tru-benh",
      bio: true,
      ai: "Streptomyces lydicus 1% w/w",
      group: "Vi sinh đối kháng (không FRAC hóa học)",
      company: "Hóa Nông Lúa Vàng (SĐK 1702/CNĐKT-BVTV)",
      targets: "Thán thư, phấn trắng, thối nhũn vi khuẩn, vàng lá thối rễ, xì mủ — sinh học.",
      crops: "Lúa, dưa, tiêu, cây có múi, sầu riêng, rau theo tài liệu phân phối.",
      dose: {
        per16: "10 g (1 gói)",
        note: "Hướng dẫn phân phối: 1 gói 10 g / bình 16 lít.",
      },
      phi: "1 ngày (nguồn phân phối).",
      mixNotes: [
        "Vi sinh sống: không pha với thuốc trừ nấm hóa học, đồng, kháng sinh, vôi.",
        "Cách ly 5–7 ngày với thuốc nấm hóa học; nếu vừa bón vôi có tài liệu khuyến cáo chờ lâu hơn.",
        "SP: hòa tan trong nước sạch, không chlorine cao. Phun sớm/chiều mát.",
      ],
      tags: ["sinh học", "vi sinh", "Streptomyces"],
    },
    {
      id: "thiamax",
      name: "Thiamax 25WG",
      form: "WG",
      kind: "tru-sau",
      bio: false,
      ai: "Thiamethoxam 250 g/kg",
      group: "IRAC 4A",
      company: "Hợp Trí",
      targets: "Rầy nâu (trứng mới nở, rầy cám, trưởng thành); lưu dẫn mạnh sau 2–3 giờ.",
      crops: "Lúa (đăng ký rầy nâu); một số kênh nêu bọ trĩ, dòi đục lá — bám nhãn lô.",
      dose: {
        per16: "4 g",
        note: "Nhãn Hợp Trí: 4 g/bình 16 lít. Phun gốc lúa, ruộng có nước.",
      },
      phi: "7 ngày.",
      mixNotes: [
        "WG: rắc vào nước khuấy, đợi nở.",
        "Không pha Mospilan hoặc Map Jono (cùng IRAC 4A).",
        "Độc ong — tránh phun khi hoa.",
      ],
      tags: ["neonicotinoid", "rầy nâu", "lưu dẫn"],
    },
  ];

  const KIND_LABEL = {
    "tru-sau": "Trừ sâu / rầy",
    "tru-benh": "Trừ bệnh",
  };

  const HARD_PAIRS = [
    {
      a: "coc",
      b: "*",
      level: "block",
      reason: "COC 85 (copper oxychloride) và Booc-đô được khuyến cáo phun riêng, khác một số đồng hydroxide.",
    },
    {
      a: "acti",
      b: "kind:tru-benh",
      level: "block",
      reason: "Streptomyces (Acti No Vate) bị diệt bởi thuốc trừ nấm/đồng/kháng sinh hóa học. Phun cách ly 5–7 ngày.",
    },
    {
      a: "dipel",
      b: "daconil",
      level: "block",
      reason: "Một số nhãn Dipel cấm phối chlorothalonil (Daconil). Không pha chung.",
    },
    {
      a: "dipel",
      b: "coc",
      level: "caution",
      reason: "Đồng kiềm có thể giảm Bt. Nếu vẫn dùng, phun ngay; tốt nhất tách buổi.",
    },
    {
      a: "dipel",
      b: "eddy",
      level: "caution",
      reason: "Eddy chứa đồng. Dipel + đồng: chỉ khi thử cốc đạt và phun ngay.",
    },
    {
      a: "acti",
      b: "dipel",
      level: "ok",
      reason: "Hai chế phẩm sinh học khác đối tượng; vẫn thử cốc và không để kiềm.",
    },
  ];

  const SAME_GROUP_RULES = [
    {
      ids: ["prevathon", "benevia"],
      group: "IRAC 28 (diamide)",
      level: "block",
      reason: "Cùng cơ chế ryanodine. Pha chung không mở phổ sâu, tăng chi phí và kháng thuốc.",
    },
    {
      ids: ["mospilan", "jono", "thiamax"],
      group: "IRAC 4A (neonicotinoid)",
      level: "block",
      reason: "Acetamiprid, imidacloprid và thiamethoxam cùng nhóm 4A. Chọn một loại; luân phiên nhóm khác.",
    },
    {
      ids: ["insuran", "phytocide", "eddy"],
      group: "FRAC 40 (dimethomorph)",
      level: "block",
      reason: "Trùng dimethomorph. Eddy đã chứa 12% dimethomorph — không cộng thêm Insuran/Phytocide.",
    },
  ];

  const SOURCES = [
    {
      title: "CropLife International — Catalogue of pesticide formulation types (Technical Monograph No. 2)",
      url: "https://croplife.org/wp-content/uploads/2023/03/Technical-Monograph-N2-8th-edition_2022_final.pdf",
      use: "Mã dạng chế phẩm WP, WG, EC, SC, OD, SP, SL… chuẩn quốc tế (FAO viện dẫn).",
    },
    {
      title: "FAO Pesticide Registration Toolkit — Type of formulation and code",
      url: "https://www.fao.org/pesticide-registration-toolkit/registration-tools/data-requirements-and-testing-guidelines/study-detail/en/c/1186059/",
      use: "Yêu cầu ghi dạng chế phẩm theo mã CropLife.",
    },
    {
      title: "Syngenta — WALES mixing order",
      url: "https://www.syngenta.ca/agronomy/wales-mixing-order",
      use: "Thứ tự: Water → WP → WDG → SC → EC → SL.",
    },
    {
      title: "Virginia Tech Extension — Spray tank mixing (WALES/DALES)",
      url: "https://pubs.ext.vt.edu/BSE/bse-351/bse-351.html",
      use: "Nguyên tắc tank-mix và thử tương hợp.",
    },
    {
      title: "The Voluntary Initiative (UK) — Tank Mix Guide 2026",
      url: "https://voluntaryinitiative.org.uk/media/bppivysf/the-vi-and-tank-mix-guide-2026_v4_tm_only.pdf",
      use: "Thứ tự chi tiết WG/WP → SC → CS → SE → EW → EC → OD → SL.",
    },
    {
      title: "Sumitomo / Valent — DiPel mixing guidelines",
      url: "https://www.sumitomobiorational.com/wp-content/uploads/2022/06/dipel-mixing-guidelines-technical-bulletin-ag-5423.pdf",
      use: "pH 4,5–8, thử cốc, phun trong 24 giờ; đồng phải phun ngay.",
    },
    {
      title: "Danh mục thuốc BVTV Việt Nam (danhmuc.thuocbvtv.com)",
      url: "https://danhmuc.thuocbvtv.com/",
      use: "Hoạt chất, cây trồng, liều ha của sản phẩm đăng ký (Dipel, Benevia, Amistar, Eddy…).",
    },
    {
      title: "Thông tư danh mục thuốc BVTV (Bộ NN&MT)",
      url: "https://luatvietnam.vn/nong-nghiep/thong-tu-28-2026-tt-bnnmt-danh-muc-thuoc-bao-ve-thuc-vat-tai-viet-nam-439351-d1.html",
      use: "Ranman 10SC (cyazofamid) và copper oxychloride trong danh mục cho phép.",
    },
    {
      title: "Nguyên tắc phối trộn BVTV (tài liệu kỹ thuật trong nước)",
      url: "https://sopphumy.com.vn/huong-dan-mot-so-nguyen-tac-phoi-tron-thuoc-bvtv.html",
      use: "WP/WG trước; SC → OD → EC; COC 85/Booc-đô phun riêng; carbamate kim loại kỵ kháng sinh.",
    },
    {
      title: "Map Pacific — Map Jono 700WP, Map Permethrin 50EC",
      url: "https://www.mappacific.com/en/product/map-jono-700wp/",
      use: "Liều imidacloprid 700 g/kg và permethrin theo nhãn hãng.",
    },
    {
      title: "Hợp Trí — Thiamax 25WG, Eddy 72WP",
      url: "https://hoptrisummit.com/san-pham/thuoc-bao-ve-thuc-vat/thuoc-tru-sau/thiamax-25wg",
      use: "Thiamethoxam 4 g/16 lít; Eddy cuprous oxide + dimethomorph.",
    },
    {
      title: "IRAC Mode of Action Classification",
      url: "https://irac-online.org/mode-of-action/",
      use: "Nhóm trừ sâu 3A, 4A, 11A, 13, 28 — không chồng cùng nhóm.",
    },
    {
      title: "FRAC Code List",
      url: "https://www.frac.info/",
      use: "Nhóm trừ bệnh 4, 7, 11, 21, 40, M01, M05 — luân phiên chống kháng.",
    },
  ];

  const formByCode = Object.fromEntries(FORMS.map((f) => [f.code, f]));
  const productById = Object.fromEntries(PRODUCTS.map((p) => [p.id, p]));

  return {
    FORMS,
    MIX_ORDER,
    PRODUCTS,
    KIND_LABEL,
    HARD_PAIRS,
    SAME_GROUP_RULES,
    SOURCES,
    formByCode,
    productById,
  };
})();
