/* Dữ liệu tra cứu pha thuốc BVTV
 * Tổng hợp từ CropLife Technical Monograph No. 2, WALES (Syngenta/Virginia Tech),
 * danh mục thuốc BVTV Việt Nam, nhãn/tài liệu kỹ thuật nhà sản xuất.
 * Luôn ưu tiên nhãn trên bao bì khi có khác biệt.
 */
window.BVTV = (function () {
  const FORMS = [
    {
      code: "WP",
      name: "Bột thấm nước",
      en: "Wettable Powder",
      vn: "BTN / BHN",
      group: "solid",
      mixStep: 1,
      color: "#7c5c2a",
      look: "Bột mịn, dễ bụi. Hòa nước tạo huyền phù đục, dễ lắng.",
      how: "Hòa thành hồ đặc trong ca nhỏ với ít nước sạch, khuấy kỹ cho hết vón. Đổ vào bình đã có 1/2–2/3 nước. Khuấy liên tục vì bột không tan hoàn toàn.",
      tips: [
        "Cần nhiều thời gian phân tán nhất — luôn cho vào trước các dạng lỏng.",
        "Đeo khẩu trang khi đổ bột, tránh hít bụi.",
        "Phun xong rửa béc kỹ; lưới lọc không nên nhỏ hơn 50 mesh.",
      ],
      avoid: "Không đổ bột khô trực tiếp vào EC/OD. Không pha khi nước phèn, nước cứng cao nếu chưa thử cốc.",
    },
    {
      code: "SP",
      name: "Bột tan trong nước",
      en: "Water Soluble Powder",
      vn: "BT",
      group: "solid",
      mixStep: 2,
      color: "#3d6b4f",
      look: "Bột; khi hòa đúng sẽ thành dung dịch trong hoặc hơi đục.",
      how: "Rắc từ từ vào nước đang khuấy. Đợi tan hết trước khi thêm thuốc khác.",
      tips: ["Tan thật sự trong nước, ít lắng hơn WP.", "Vẫn hòa riêng rồi mới đổ vào bình."],
      avoid: "Không trộn bột khô với thuốc đậm đặc.",
    },
    {
      code: "WG",
      name: "Hạt phân tán trong nước",
      en: "Water Dispersible Granule (WDG / DF)",
      vn: "HHN",
      group: "solid",
      mixStep: 3,
      color: "#8a6d3b",
      look: "Cốm/hạt nhỏ, ít bụi hơn WP. Nở và phân tán khi gặp nước.",
      how: "Rắc từ từ vào nước đang khuấy, đợi hạt tan hết (1–3 phút) rồi mới thêm thuốc khác.",
      tips: [
        "An toàn hơn WP vì ít bụi.",
        "Cho sau WP nếu pha chung hai dạng bột.",
        "Một số tài liệu quốc tế (WALES) cho WG ngay sau WP.",
      ],
      avoid: "Không đổ hạt vào dung dịch đã có nhiều dầu EC — hạt khó nở.",
    },
    {
      code: "SG",
      name: "Hạt tan trong nước",
      en: "Water Soluble Granule",
      vn: "HT",
      group: "solid",
      mixStep: 3,
      color: "#4a7c59",
      look: "Hạt tan hoàn toàn thành dung dịch.",
      how: "Cho vào nước đang khuấy, đợi tan hết.",
      tips: ["Khác GR/G/H: SG dùng để phun; GR/G/H là hạt rải gốc — không hòa nước phun."],
      avoid: "Không nhầm với thuốc hạt rải (GR, G, H).",
    },
    {
      code: "SC",
      name: "Huyền phù đậm đặc",
      en: "Suspension Concentrate (Flowable)",
      vn: "HF",
      group: "liquid-water",
      mixStep: 4,
      color: "#1d4e89",
      look: "Sệt, đục. Hoạt chất rắn lơ lửng trong nước.",
      how: "Lắc chai thật kỹ trước khi rót. Cho vào bình sau khi dạng bột đã phân tán đều.",
      tips: ["Dễ lắng trong chai — lắc là bắt buộc.", "Khuấy lại khi phun gián đoạn."],
      avoid: "Không đổ SC đặc vào EC chưa pha loãng.",
    },
    {
      code: "CS",
      name: "Huyền phù vi nang",
      en: "Capsule Suspension",
      vn: "Vi nang",
      group: "liquid-water",
      mixStep: 5,
      color: "#2563a8",
      look: "Huyền phù; hoạt chất bọc nang, nhả chậm.",
      how: "Lắc đều. Cho sau SC thông thường theo một số hướng dẫn tank-mix.",
      tips: ["Giữ hiệu lực kéo dài.", "Không nghiền/phá nang bằng cách khuấy quá mạnh không cần thiết."],
      avoid: "Một số CS kỵ dung môi mạnh của EC — thử cốc trước.",
    },
    {
      code: "OD",
      name: "Huyền phù trong dầu",
      en: "Oil Dispersion",
      vn: "Dầu phân tán",
      group: "liquid-oil",
      mixStep: 6,
      color: "#b45309",
      look: "Sệt, gốc dầu. Bám lá tốt, dễ gây váng nếu pha sai thứ tự.",
      how: "Lắc chai. Cho sau SC, trước EC. Khuấy đều ngay.",
      tips: ["Benevia 100OD thuộc dạng này.", "Nhạy với nước bẩn và pha vội."],
      avoid: "Không đổ OD vào bột chưa tan. Tránh nắng gắt — dầu dễ cháy lá.",
    },
    {
      code: "EC",
      name: "Nhũ dầu đậm đặc",
      en: "Emulsifiable Concentrate",
      vn: "ND / thuốc sữa",
      group: "liquid-oil",
      mixStep: 7,
      color: "#c2410c",
      look: "Lỏng, thường có mùi dung môi. Pha nước thành sữa đục.",
      how: "Cho gần cuối nhóm thuốc, sau khi mọi dạng rắn và SC đã phân tán. Khuấy tạo nhũ ổn định.",
      tips: [
        "Loang trải, bám dính tốt, chịu mưa hơn nhiều dạng khác.",
        "Tăng liều + nắng nóng = rủi ro cháy lá cao.",
        "Hai loại EC trong một bình dễ quá tải dung môi — hạn chế.",
      ],
      avoid: "Không cho EC vào trước WP/WG. Không pha với nước phèn.",
    },
    {
      code: "EW",
      name: "Nhũ tương dầu trong nước",
      en: "Emulsion, oil-in-water",
      vn: "Nhũ tương",
      group: "liquid-oil",
      mixStep: 7,
      color: "#d97706",
      look: "Sữa, ít mùi dung môi hơn EC.",
      how: "Cho cùng bước với EC, sau SC/OD.",
      tips: ["Mềm hơn EC với cây trồng."],
      avoid: "Vẫn thử cốc khi phối nhiều loại.",
    },
    {
      code: "ME",
      name: "Vi nhũ",
      en: "Micro-emulsion",
      vn: "Vi nhũ",
      group: "liquid-oil",
      mixStep: 7,
      color: "#ca8a04",
      look: "Trong đến hơi đục; hạt nhũ rất nhỏ.",
      how: "Cho cùng nhóm EC/EW.",
      tips: ["Ổn định hơn EC thông thường."],
      avoid: "",
    },
    {
      code: "SL",
      name: "Dung dịch tan trong nước",
      en: "Soluble Concentrate / Soluble Liquid",
      vn: "DD",
      group: "liquid-water",
      mixStep: 8,
      color: "#0f766e",
      look: "Lỏng trong hoặc hơi opalescent. Tan thành dung dịch thật.",
      how: "Cho sau EC theo WALES. Hòa dễ, ít cần thời gian khuấy.",
      tips: ["Một số hướng dẫn VN xếp SL cùng EC ở bước cuối nhóm thuốc."],
      avoid: "",
    },
    {
      code: "SE",
      name: "Huyền phù-nhũ tương",
      en: "Suspo-emulsion",
      vn: "SE",
      group: "liquid-water",
      mixStep: 5,
      color: "#1e40af",
      look: "Vừa hạt rắn vừa giọt dầu trong nước.",
      how: "Lắc kỹ. Cho sau SC, trước EC.",
      tips: ["Khuấy liên tục khi phun."],
      avoid: "",
    },
    {
      code: "GR",
      name: "Hạt rải gốc",
      en: "Granule",
      vn: "G / H",
      group: "not-spray",
      mixStep: 0,
      color: "#57534e",
      look: "Hạt rắn dùng rải đất, không pha nước phun.",
      how: "Rải theo hàng/gốc theo nhãn. Không hòa vào bình phun.",
      tips: ["Ký hiệu GR, G, H trên nhãn Việt Nam thường là hạt rải."],
      avoid: "Không pha vào bình phun lá.",
    },
    {
      code: "ULV",
      name: "Phun lượng cực nhỏ",
      en: "Ultra Low Volume",
      vn: "ULV",
      group: "special",
      mixStep: 0,
      color: "#44403c",
      look: "Đậm đặc, dùng máy ULV, ít hoặc không pha nước.",
      how: "Theo máy và nhãn. Không dùng như thuốc pha bình đeo vai.",
      tips: [],
      avoid: "Không đổ ULV vào bình phun nước thông thường trừ khi nhãn cho phép.",
    },
    {
      code: "FS",
      name: "Huyền phù xử lý hạt",
      en: "Flowable concentrate for seed treatment",
      vn: "Xử lý hạt",
      group: "special",
      mixStep: 0,
      color: "#57534e",
      look: "Dùng trộn hạt giống, không phun lá.",
      how: "Trộn hạt theo nhãn.",
      tips: [],
      avoid: "Không dùng để phun cây.",
    },
    {
      code: "DP",
      name: "Bột rắc",
      en: "Dustable powder",
      vn: "Bột rắc",
      group: "not-spray",
      mixStep: 0,
      color: "#78716c",
      look: "Bột khô rắc trực tiếp, không hòa nước.",
      how: "Rắc theo nhãn.",
      tips: [],
      avoid: "Không pha bình phun.",
    },
  ];

  const MIX_ORDER = [
    {
      step: 0,
      title: "Nước sạch",
      detail: "Đổ 1/2 đến 2/3 bình. Bật khuấy (hoặc khuấy tay liên tục). Nước phèn, nước ao, nước cứng cao làm hỏng nhiều loại thuốc — đặc biệt sinh học và EC.",
      codes: [],
    },
    {
      step: 1,
      title: "Bột thấm nước — WP",
      detail: "Hòa hồ đặc riêng, đổ vào, khuấy đến khi không còn vón. Đây là bước khó tan nhất.",
      codes: ["WP"],
    },
    {
      step: 2,
      title: "Bột tan — SP",
      detail: "Cho vào khi WP đã phân tán. Đợi tan hết.",
      codes: ["SP"],
    },
    {
      step: 3,
      title: "Hạt phân tán / hạt tan — WG, SG",
      detail: "Rắc từ từ. Đợi hạt nở và phân tán 1–3 phút.",
      codes: ["WG", "SG"],
    },
    {
      step: 4,
      title: "Huyền phù nước — SC, CS, SE",
      detail: "Lắc chai. Cho từng loại, khuấy đều giữa mỗi lần.",
      codes: ["SC", "CS", "SE"],
    },
    {
      step: 5,
      title: "Dạng dầu — OD",
      detail: "Cho sau mọi dạng nước. Khuấy tạo hỗn hợp đồng nhất.",
      codes: ["OD"],
    },
    {
      step: 6,
      title: "Nhũ dầu — EC, EW, ME",
      detail: "Cho gần cuối nhóm thuốc. Tạo sữa đục ổn định.",
      codes: ["EC", "EW", "ME"],
    },
    {
      step: 7,
      title: "Dung dịch — SL",
      detail: "Theo WALES, SL vào sau EC. Hòa nhanh.",
      codes: ["SL"],
    },
    {
      step: 8,
      title: "Phân bón lá / vi lượng",
      detail: "Hòa riêng, liều thấp, cho sau thuốc. Không dùng khi cây đang bệnh nặng (đạm làm bệnh lan).",
      codes: [],
    },
    {
      step: 9,
      title: "Chất bám dính / trải",
      detail: "Cho cuối cùng. Châm nước đủ bình, khuấy, phun ngay. Không để qua đêm.",
      codes: [],
    },
  ];

  const PRODUCTS = [
    {
      id: "dipel",
      name: "Dipel 6.4WG",
      form: "WG",
      kind: "tru-sau",
      bio: true,
      ai: "Bacillus thuringiensis var. kurstaki 64 g/kg (32.000 IU/mg)",
      group: "IRAC 11A",
      company: "Sumitomo",
      pack: "50 g",
      targets: "Sâu tơ, sâu cuốn lá, bọ xít muỗi, sâu keo — tiếp xúc + đường ruột (sâu phải ăn phải thuốc).",
      crops: "Cải bắp, chè và rau ăn lá theo nhãn.",
      dose: {
        per16: "40 g",
        per1000: "100 g / 40 lít nước",
        note: "Bảng pha vườn: 100 g / 40 lít / 1000 m² (pha 1:800, khoảng 1:267–1:5000). Gói 50 g.",
      },
      phi: "1 ngày.",
      mixNotes: [
        "Sinh học: pH nước nên 4,5–8. Nước kiềm làm giảm hiệu lực.",
        "Có thể phối nhiều thuốc hóa học nếu thử cốc đạt; phun trong ngày.",
        "Đồng: một số tài liệu Dipel cho phép phối nhưng phải phun ngay. Booc-đô, vôi lưu huỳnh: không phối.",
      ],
      tags: ["sinh học", "Bt", "sâu ăn lá"],
    },
    {
      id: "secure",
      name: "SECURE 10EC",
      form: "EC",
      kind: "tru-sau",
      bio: false,
      ai: "Chlorfenapyr 100 g/l",
      group: "IRAC 13",
      company: "Hợp Trí / phổ biến trên thị trường VN",
      pack: "40 ml",
      targets: "Sâu tơ, sâu xanh, sâu cuốn lá, bọ trĩ, nhện đỏ — tiếp xúc + vị độc, ngấm mô; hữu ích khi sâu đã kháng cúc, lân, carbamate.",
      crops: "Lúa, dưa hấu, cây có múi, đậu theo nhãn.",
      dose: {
        per16: "10,7 ml",
        per1000: "30 ml / 45 lít nước",
        note: "Bảng pha vườn: 30 ml / 45 lít / 1000 m² (pha 1:1500, khoảng 1:595–1:2083). Chai 40 ml.",
      },
      phi: "14 ngày.",
      mixNotes: [
        "Dạng EC: cho vào bình gần cuối, sau WP/WG/SC.",
        "Hạn chế pha chung với EC khác (Neem, Permethrin, Mospilan) vì tăng dung môi, dễ cháy lá.",
        "Không tăng liều khi nắng gắt.",
      ],
      tags: ["nhũ dầu", "sâu kháng"],
    },
    {
      id: "prevathon",
      name: "Dupont Prevathon 5SC",
      form: "SC",
      kind: "tru-sau",
      bio: false,
      ai: "Chlorantraniliprole 50 g/l (5%)",
      group: "IRAC 28",
      company: "FMC (trước đây DuPont)",
      targets: "Sâu cuốn lá, sâu đục thân, sâu tơ, bọ nhảy, dòi đục lá, sâu xanh — sâu ngừng ăn nhanh.",
      crops: "Lúa, bắp cải, cà chua, dưa hấu, đậu, hành theo nhãn.",
      dose: {
        per16: "15 ml",
        note: "Hướng dẫn phổ biến: 15 ml/bình 16 lít hoặc 25 ml/bình 25 lít. Không phun quá 2 lần/vụ trên một số cây.",
      },
      phi: "1–3 ngày tùy cây (cà chua/dưa 1 ngày; lúa/bắp cải khoảng 3 ngày — đối chiếu nhãn).",
      mixNotes: [
        "Lắc gói/chai trước khi rót.",
        "Không pha chung Benevia 100OD hoặc Dupont Prevathon 200SC: cùng IRAC 28 / cùng chlorantraniliprole.",
        "Cho vào sau dạng bột, trước EC/OD.",
      ],
      tags: ["diamide", "lưu dẫn cục bộ", "prevathon"],
    },
    {
      id: "prevathon200",
      name: "Dupont Prevathon 200SC",
      form: "SC",
      kind: "tru-sau",
      bio: false,
      ai: "Chlorantraniliprole 200 g/l",
      group: "IRAC 28",
      company: "FMC",
      pack: "25 ml",
      targets: "Sâu đục thân, sâu cuốn lá, sâu tơ, bọ nhảy, dòi đục lá, sâu xanh, sâu đục trái — tiếp xúc + vị độc, thấm sâu/lưu dẫn hạn chế. Nồng độ cao hơn loại 5SC.",
      crops: "Theo nhãn lô. Cùng cây cấm với Prevathon 5SC — xem bộ Tra pha.",
      dose: {
        per16: "6 ml",
        per1000: "17 ml / 45 lít nước",
        note: "Bảng pha vườn: 17 ml / 45 lít / 1000 m² (pha ~1:2647). Chai 25 ml. Không dùng liều kiểu Prevathon 5SC.",
      },
      phi: "7 ngày.",
      mixNotes: [
        "Không pha Dupont Prevathon 5SC (trùng chlorantraniliprole) hoặc Benevia (cùng IRAC 28).",
        "Lắc chai. Cho bước SC.",
      ],
      tags: ["diamide", "prevathon", "200sc"],
    },
    {
      id: "benevia",
      name: "BENEVIA 100OD",
      form: "OD",
      kind: "tru-sau",
      bio: false,
      ai: "Cyantraniliprole 100 g/l",
      group: "IRAC 28",
      company: "FMC",
      targets: "Bọ trĩ, rầy mềm, rầy phấn trắng, sâu tơ, sâu xanh, sâu khoang, vẽ bùa — nội hấp/lưu dẫn + tiếp xúc + vị độc.",
      crops: "Cà chua, dưa hấu, dưa chuột, ớt, lúa, xoài theo nhãn.",
      dose: {
        per16: "25,6 ml",
        per1000: "80 ml / 50 lít nước",
        note: "Bảng pha vườn: 80 ml / 50 lít / 1000 m² (pha 1:625).",
      },
      phi: "14 ngày.",
      mixNotes: [
        "Dạng OD: cho sau SC, trước hoặc thay bước EC.",
        "Không pha với Prevathon 5SC hoặc Dupont Prevathon 200SC (cùng IRAC 28).",
        "Lắc kỹ. Tránh nắng gắt vì gốc dầu.",
      ],
      tags: ["diamide", "bọ trĩ", "dầu"],
    },
    {
      id: "permethrin",
      name: "Map-Permethrin 50EC",
      form: "EC",
      kind: "tru-sau",
      bio: false,
      ai: "Permethrin 500 g/l",
      group: "IRAC 3A",
      company: "Map Pacific",
      pack: "480 ml",
      targets: "Rệp sáp, bọ xít muỗi, sâu cuốn lá, sâu xanh da láng, sâu đục quả — tiếp xúc + vị độc.",
      crops: "Lúa, lạc, đậu nành, cà phê, điều theo nhãn Map.",
      dose: {
        per16: "8 ml",
        per1000: "25 ml / 50 lít nước",
        note: "Bảng pha vườn: 25 ml / 50 lít / 1000 m² (pha 1:2000, khoảng 1:1501–1:2500). Chai 480 ml.",
      },
      phi: "14 ngày.",
      mixNotes: [
        "Cúc tổng hợp: độc với ong, cá, thiên địch — không phun khi hoa nở rộ.",
        "Hạn chế pha 2 EC. Cho vào cuối nhóm thuốc.",
      ],
      tags: ["cúc tổng hợp", "tiếp xúc"],
    },
    {
      id: "mospilan",
      name: "Mospilan 3EC",
      form: "EC",
      kind: "tru-sau",
      bio: false,
      ai: "Acetamiprid 3% w/w",
      group: "IRAC 4A",
      company: "Summit / Ishihara",
      pack: "80 ml",
      targets: "Rầy nâu, bọ trĩ, rệp muội, rệp sáp, rầy — nội hấp + tiếp xúc + vị độc.",
      crops: "Lúa, cà phê, hồ tiêu, vừng, bông vải theo nhãn.",
      dose: {
        per16: "21 ml",
        per1000: "80 ml / 60 lít nước",
        note: "Bảng pha vườn: 80 ml / 60 lít / 1000 m² (pha 1:750, khoảng 1:446–1:833). Chai 80 ml.",
      },
      phi: "14 ngày.",
      mixNotes: [
        "Cùng nhóm 4A với Map Jono / Mikhada / Anvado, Thiamax / Actara và Dantotsu — không pha chung.",
        "Dạng EC: bước nhũ dầu.",
      ],
      tags: ["neonicotinoid", "rầy", "rệp"],
    },
    {
      id: "jono",
      name: "MAP JONO 700WP",
      form: "WP",
      kind: "tru-sau",
      bio: false,
      ai: "Imidacloprid 700 g/kg",
      group: "IRAC 4A",
      company: "Map Pacific",
      pack: "40 g",
      targets: "Rầy nâu, rầy xanh chích hút — nội hấp + tiếp xúc + vị độc. Hàm lượng cao nên liều gam rất nhỏ.",
      crops: "Lúa, ngô, bông vải theo nhãn Map.",
      dose: {
        per16: "1,6 g",
        per1000: "4 g / 40 lít nước",
        note: "Bảng pha vườn: 4 g / 40 lít / 1000 m² (pha 1:10000). Gói 40 g. Dùng cân/gói định lượng, không ước chừng.",
      },
      phi: "7 ngày.",
      mixNotes: [
        "WP: hòa hồ đặc trước, cho vào bình đầu tiên trong các thuốc.",
        "Cùng imidacloprid với Mikhada 10WP và Anvado 100WP — chọn một chai, không cộng liều.",
        "Không pha với Mospilan, Thiamax, Actara hoặc Dantotsu (cùng IRAC 4A).",
      ],
      tags: ["neonicotinoid", "rầy", "bột", "jono", "imidacloprid"],
    },
    {
      id: "mikhada",
      name: "Mikhada 10WP",
      form: "WP",
      kind: "tru-sau",
      bio: false,
      ai: "Imidacloprid 100 g/kg (10%)",
      group: "IRAC 4A",
      company: "Phổ biến trên thị trường VN",
      targets: "Rầy, rệp, bọ trĩ — cùng hoạt chất MAP JONO và Anvado, hàm lượng thấp hơn Jono 700WP.",
      crops: "Theo nhãn. Cùng cây cấm với Map Jono — xem bộ Tra pha.",
      dose: {
        per16: "Theo nhãn",
        note: "10% imidacloprid: liều gam lớn hơn MAP JONO 700WP rất nhiều. Không lấy 1,6 g của Jono áp cho Mikhada.",
      },
      phi: "Theo nhãn.",
      mixNotes: [
        "WP: hòa hồ đặc trước.",
        "Không pha MAP JONO, Anvado (trùng imidacloprid) hay Mospilan / Thiamax / Actara / Dantotsu (IRAC 4A).",
      ],
      tags: ["neonicotinoid", "mikhada", "imidacloprid", "rầy"],
    },
    {
      id: "anvado",
      name: "Anvado 100WP",
      form: "WP",
      kind: "tru-sau",
      bio: false,
      ai: "Imidacloprid 100 g/kg",
      group: "IRAC 4A",
      company: "Phổ biến trên thị trường VN",
      targets: "Rầy, rệp — cùng hoạt chất MAP JONO và Mikhada.",
      crops: "Theo nhãn. Cùng cây cấm với Map Jono — xem bộ Tra pha.",
      dose: {
        per16: "Theo nhãn",
        note: "Hàm lượng khác MAP JONO 700WP. Đọc nhãn Anvado, không chép liều Jono.",
      },
      phi: "Theo nhãn.",
      mixNotes: [
        "WP: hòa hồ đặc trước.",
        "Không pha MAP JONO, Mikhada (trùng imidacloprid) hay nhóm 4A khác.",
      ],
      tags: ["neonicotinoid", "anvado", "imidacloprid", "rầy"],
    },
    {
      id: "amistar",
      name: "Amistar 250SC",
      form: "SC",
      kind: "tru-benh",
      bio: false,
      ai: "Azoxystrobin 250 g/l",
      group: "FRAC 11",
      company: "Syngenta",
      pack: "100 g",
      targets: "Phấn trắng, đốm lá, thán thư, sương mai, đốm vòng, khô vằn, đốm nâu, mốc sương, lở cổ rễ — thấm sâu + lưu dẫn + nội hấp. Dễ kháng: không lạm dụng.",
      crops: "Cam, xoài, cà chua, dưa hấu, ớt, thanh long, chuối theo nhãn.",
      dose: {
        per16: "10,7 ml",
        per1000: "30 ml / 45 lít nước",
        note: "Bảng pha vườn: 30 ml / 45 lít / 1000 m² (pha 1:1500, khoảng 1:1250–1:1666). Ghi dung tích 100 g trên bảng pha.",
      },
      phi: "14 ngày.",
      mixNotes: [
        "Lắc chai. Cho bước SC.",
        "Nên phối hoặc luân phiên với thuốc đa vị trí (đồng) để chống kháng strobilurin.",
        "Không thay thế thuốc trị khi bệnh đã nặng trên một số đối tượng — chủ yếu phòng và chớm bệnh.",
      ],
      tags: ["strobilurin", "nội hấp"],
    },
    {
      id: "ranman",
      name: "Ranman 10SC",
      form: "SC",
      kind: "tru-benh",
      bio: false,
      ai: "Cyazofamid 100 g/l",
      group: "FRAC 21",
      company: "Nichino / Sumitomo (đăng ký VN)",
      pack: "40 ml",
      targets: "Sương mai, mốc sương, héo rũ (Oomycete) — tiếp xúc + thấm sâu.",
      crops: "Nho, cà chua, dưa leo, dưa hấu, khoai môn theo nhãn.",
      dose: {
        per16: "18 ml",
        per1000: "50 ml / 45 lít nước",
        note: "Bảng pha vườn: 50 ml / 45 lít / 1000 m² (pha 1:900, khoảng 1:900–1:950). Chai 40 ml.",
      },
      phi: "7 ngày.",
      mixNotes: [
        "Lắc kỹ. Bước SC.",
        "Đặc trị oomycete — không thay thế thuốc thán thư/phấn trắng do nấm thật.",
        "Có thể cân nhắc luân phiên với dimethomorph (Insuran/Phytocide) vì khác FRAC.",
      ],
      tags: ["oomycete", "sương mai"],
    },
    {
      id: "metaxyl",
      name: "METAXYL 25WP",
      form: "WP",
      kind: "tru-benh",
      bio: false,
      ai: "Metalaxyl 25%",
      group: "FRAC 4",
      company: "Nhiều nhà (cùng hoạt chất)",
      pack: "100 g",
      targets: "Thối gốc, lở cổ rễ, sương mai, mốc phấn trắng — nội hấp/lưu dẫn. Dễ kháng.",
      crops: "Rau, hồ tiêu, sắn, cà chua, khoai tây theo nhãn lô.",
      dose: {
        per16: "18 g",
        per1000: "50 g / 45 lít nước",
        note: "Bảng pha vườn: 50 g / 45 lít / 1000 m² (pha 1:900, khoảng 1:842–1:1280). Gói 100 g.",
      },
      phi: "14 ngày.",
      mixNotes: [
        "Nên phối với thuốc tiếp xúc (mancozeb, đồng dạng phù hợp) vì metalaxyl đơn độc dễ mất hiệu lực do kháng.",
        "Hòa WP trước. Một số tài liệu cho phép phối COC — vẫn thử cốc; COC 85 khuyến cáo phun riêng.",
      ],
      tags: ["phenylamide", "Phytophthora"],
    },
    {
      id: "insuran",
      name: "INSURAN 50WP",
      form: "WP",
      kind: "tru-benh",
      bio: false,
      ai: "Dimethomorph 50% (500 g/kg)",
      group: "FRAC 40",
      company: "Phổ biến trên thị trường VN",
      pack: "100 g",
      targets: "Sương mai, mốc sương, thối gốc — thấm sâu + lưu dẫn cục bộ.",
      crops: "Tiêu, cà chua, dưa, vải, sầu riêng, cao su theo nhãn.",
      dose: {
        per16: "32 g",
        per1000: "100 g / 50 lít nước",
        note: "Bảng pha vườn: 100 g / 50 lít / 1000 m² (pha 1:500, khoảng 1:277–1:5000). Gói 100 g.",
      },
      phi: "14 ngày.",
      mixNotes: [
        "Không pha với Phytocide hoặc Eddy: trùng dimethomorph (FRAC 40).",
        "WP: hòa trước. Thường phối thuốc tiếp xúc khác nhóm.",
      ],
      tags: ["CAA", "Phytophthora"],
    },
    {
      id: "phytocide",
      name: "Phytocide 50WP",
      form: "WP",
      kind: "tru-benh",
      bio: false,
      ai: "Dimethomorph 500 g/kg",
      group: "FRAC 40",
      company: "Phổ biến trên thị trường VN",
      pack: "80 g",
      targets: "Sương mai, mốc sương, thối gốc — thấm sâu + lưu dẫn cục bộ.",
      crops: "Cà chua, tiêu, dưa hấu, vải, cao su theo nhãn.",
      dose: {
        per16: "16 g",
        per1000: "40 g / 40 lít nước",
        note: "Bảng pha vườn: 40 g / 40 lít / 1000 m² (pha 1:1000). Gói 80 g.",
      },
      phi: "14 ngày.",
      mixNotes: [
        "Không pha Insuran hoặc Eddy (cùng dimethomorph).",
        "Một hướng dẫn gợi ý phối Norshield (đồng hydroxide) — khác COC 85. COC 85 vẫn nên phun riêng.",
      ],
      tags: ["CAA", "Phytophthora"],
    },
    {
      id: "eddy",
      name: "EDDY 72WP",
      form: "WP",
      kind: "tru-benh",
      bio: false,
      ai: "Cuprous oxide 60% + Dimethomorph 12%",
      group: "FRAC M01 + 40",
      company: "Hợp Trí Summit",
      pack: "300 g",
      targets: "Sương mai, mốc sương, thối gốc — thấm sâu/lưu dẫn cục bộ + tiếp xúc (đồng + dimethomorph).",
      crops: "Tiêu, sầu riêng, ca cao, cà phê, khoai tây theo nhãn.",
      dose: {
        per16: "48 g",
        per1000: "120 g / 40 lít nước",
        note: "Bảng pha vườn (phun lá): 120 g / 40 lít / 1000 m² (pha 1:333, khoảng 1:333–1:500). Gói 300 g. Tưới gốc tiêu trên nhãn có thể khác — ưu tiên bảng pha khi phun lá.",
      },
      phi: "14 ngày.",
      mixNotes: [
        "Đã chứa đồng + dimethomorph: không pha thêm COC 85, Insuran, Phytocide.",
        "Gốc đồng: hạn chế phối kháng sinh, fosetyl-Al, phân bón lá.",
        "WP: hòa kỹ, khuấy liên tục.",
      ],
      tags: ["đồng", "Phytophthora", "kép"],
    },
    {
      id: "kimono",
      name: "KIMONO APC 50WG",
      form: "WG",
      kind: "tru-benh",
      bio: false,
      ai: "Boscalid 50% w/w",
      group: "FRAC 7",
      company: "Đăng ký 6938/CNĐKT-BVTV",
      pack: "50 g",
      targets: "Thán thư, phấn trắng, đốm lá — nội hấp/lưu dẫn (SDHI). Dễ kháng — luân phiên nhóm khác.",
      crops: "Đậu tương (đăng ký sương mai) và cây khác theo nhãn lô.",
      dose: {
        per16: "8 g",
        per1000: "20 g / 40 lít nước",
        note: "Bảng pha vườn: 20 g / 40 lít / 1000 m² (pha 1:2000). Gói 50 g.",
      },
      phi: "14 ngày.",
      mixNotes: [
        "WG: rắc vào nước đang khuấy, đợi nở hết.",
        "Khác nhóm với Amistar (11), Ranman (21) — phù hợp luân phiên.",
      ],
      tags: ["SDHI", "boscalid"],
    },
    {
      id: "coc",
      name: "COC 85WP",
      form: "WP",
      kind: "tru-benh",
      bio: false,
      ai: "Copper oxychloride 85% (tương đương Cu hữu hiệu theo nhãn)",
      group: "FRAC M01",
      company: "Nhiều nhà (COC 85 là tên hoạt chất/dạng phổ biến)",
      pack: "20 g",
      targets: "Cháy lá vi khuẩn, loét vi khuẩn, thán thư — tiếp xúc/bề mặt, rửa trôi nếu mưa.",
      crops: "Điều, cây ăn trái, rau theo từng sản phẩm đăng ký.",
      dose: {
        per16: "40 g",
        per1000: "100 g / 40 lít nước",
        note: "Bảng pha vườn: 100 g / 40 lít / 1000 m² (pha 1:400, khoảng 1:200–1:400). Gói 20 g. ≈ 0,25% (2,5 g/lít).",
      },
      phi: "1 ngày.",
      mixNotes: [
        "Khuyến cáo kỹ thuật VN: CuSO4, COC 85 và Booc-đô chỉ nên phun riêng — khác các đồng hydroxide (Kocide, Champion) có thể phối một số hoạt chất.",
        "Không phối kháng sinh BVTV, fosetyl-Al, phân bón lá.",
        "Kiềm: có thể làm giảm Bt (Dipel) nếu không phun ngay; Acti No Vate (vi sinh) không phối.",
      ],
      tags: ["đồng", "tiếp xúc", "phun riêng"],
    },
    {
      id: "neem",
      name: "Neem Nim 0.3EC",
      form: "EC",
      kind: "tru-sau",
      bio: true,
      ai: "Azadirachtin 0,3% (chiết xuất neem)",
      group: "IRAC UN (botanical) / chống ăn, IGR",
      company: "Thảo mộc — đối chiếu nhãn lô",
      pack: "500 ml",
      targets: "Ruồi đục lá, bọ trĩ, sâu tơ, sâu xanh da láng, rệp sáp, tuyến trùng, nhện đỏ, rầy phấn — tiếp xúc + vị độc + ức chế ăn/lột xác, không diệt tức thì.",
      crops: "Rau, cây ăn trái theo nhãn.",
      dose: {
        per16: "40 ml",
        per1000: "100 ml / 40 lít nước",
        note: "Bảng pha vườn: 100 ml / 40 lít / 1000 m² (pha 1:400, khoảng 1:320–1:533). Chai 500 ml. Lắc đều. Phun sớm, lặp lại.",
      },
      phi: "1 ngày.",
      mixNotes: [
        "EC thảo mộc: hạn chế pha thêm EC hóa học (Secure, Permethrin, Mospilan) — dễ cháy lá.",
        "Không phối chất kiềm (Booc-đô, vôi). Nắng gắt + dầu = cháy lá.",
        "Hiệu lực chậm: không kỳ vọng thay thuốc độc thần kinh khi mật độ sâu đã rất cao.",
      ],
      tags: ["thảo mộc", "neem", "rau an toàn"],
    },
    {
      id: "acti",
      name: "Acti No Vate 1SP",
      form: "SP",
      kind: "tru-benh",
      bio: true,
      ai: "Streptomyces lydicus 1% w/w",
      group: "Vi sinh đối kháng (không FRAC hóa học)",
      company: "Hóa Nông Lúa Vàng (SĐK 1702/CNĐKT-BVTV)",
      pack: "10 g",
      targets: "Sương mai, phấn trắng, thán thư, nứt dây chảy nhựa — sinh học (Streptomyces).",
      crops: "Dưa hấu, dưa chuột, bầu bí, cà chua, ớt; lúa, tiêu, cây có múi, sầu riêng theo tài liệu phân phối.",
      dose: {
        per16: "10 g (1 gói)",
        per1000: "25 g / 40 lít nước",
        note: "Bảng pha vườn: 25 g / 40 lít / 1000 m² (pha 1:1600) ≈ 1 gói 10 g / bình 16 lít.",
      },
      phi: "14 ngày.",
      mixNotes: [
        "Vi sinh sống: không pha với thuốc trừ nấm hóa học, đồng, kháng sinh, vôi.",
        "Cách ly 5–7 ngày với thuốc nấm hóa học; nếu vừa bón vôi có tài liệu khuyến cáo chờ lâu hơn.",
        "SP: hòa tan trong nước sạch, không chlorine cao. Phun sớm/chiều mát.",
      ],
      tags: ["sinh học", "vi sinh", "Streptomyces"],
    },
    {
      id: "thiamax",
      name: "Thiamax 25WG",
      form: "WG",
      kind: "tru-sau",
      bio: false,
      ai: "Thiamethoxam 250 g/kg",
      group: "IRAC 4A",
      company: "Hợp Trí",
      targets: "Rầy cánh dài, dòi đục lá, bọ trĩ, bọ phấn — nội hấp + tiếp xúc + vị độc.",
      crops: "Lúa (đăng ký rầy nâu); một số kênh nêu bọ trĩ, dòi đục lá — bám nhãn lô.",
      dose: {
        per16: "1,6 g",
        per1000: "4,5 g / 45 lít nước",
        note: "Bảng pha vườn: 4,5 g / 45 lít / 1000 m² (pha 1:10000). Phun gốc lúa, ruộng có nước.",
      },
      phi: "7 ngày.",
      mixNotes: [
        "WG: rắc vào nước khuấy, đợi nở.",
        "Cùng thiamethoxam với Actara 25WG — chọn một chai.",
        "Không pha Mospilan, Map Jono, Mikhada, Anvado hoặc Dantotsu (cùng IRAC 4A).",
        "Độc ong — tránh phun khi hoa.",
      ],
      tags: ["neonicotinoid", "rầy nâu", "lưu dẫn", "actara", "thiamethoxam"],
    },
    {
      id: "actara",
      name: "Actara 25WG",
      form: "WG",
      kind: "tru-sau",
      bio: false,
      ai: "Thiamethoxam 250 g/kg",
      group: "IRAC 4A",
      company: "Syngenta",
      targets: "Rầy nâu, rệp, bọ trĩ — cùng hoạt chất Thiamax 25WG.",
      crops: "Theo nhãn Syngenta. Cùng cây cấm với Thiamax — xem bộ Tra pha.",
      dose: {
        per16: "4 g",
        note: "Nhiều hướng dẫn lúa ~4 g/bình 16 lít (cùng nhóm 25WG với Thiamax). Vẫn đối chiếu nhãn Actara đang cầm.",
      },
      phi: "Theo nhãn (thường khoảng 7 ngày).",
      mixNotes: [
        "WG: rắc vào nước khuấy, đợi nở.",
        "Không pha Thiamax (trùng thiamethoxam) hay Mospilan / Jono / Mikhada / Anvado / Dantotsu (IRAC 4A).",
        "Độc ong — tránh phun khi hoa.",
      ],
      tags: ["neonicotinoid", "actara", "thiamethoxam", "rầy"],
    },
    {
      id: "kanaka",
      name: "Kanaka 405WP",
      form: "WP",
      kind: "tru-benh",
      bio: false,
      ai: "Myclobutanil 405 g/kg",
      group: "FRAC 3",
      company: "Phổ biến trên thị trường VN",
      targets: "Phấn trắng, thán thư, đốm lá — triazole, nội hấp.",
      crops: "Theo nhãn. Cấm nhiều rau ăn lá, hành tây, cải, bí — xem bộ Tra pha.",
      dose: {
        per16: "Theo nhãn",
        note: "Đối chiếu nhãn cây đang trồng. Dễ kháng nếu lặp cùng nhóm FRAC 3.",
      },
      phi: "Theo nhãn.",
      mixNotes: ["WP: hòa hồ đặc trước, cho vào sớm.", "Luân phiên nhóm khác (không chồng triazole)."],
      tags: ["triazole", "myclobutanil", "phấn trắng"],
    },
    {
      id: "cylen",
      name: "CYLEN 500WP",
      form: "WP",
      kind: "tru-benh",
      bio: false,
      ai: "Dimethomorph 500 g/kg",
      group: "FRAC 40",
      company: "Phổ biến trên thị trường VN",
      targets: "Sương mai, giả sương mai, Phytophthora — cùng hoạt chất Insuran/Phytocide.",
      crops: "Theo nhãn. Cấm một số hành, cải, cà rốt — xem bộ Tra pha.",
      dose: {
        per16: "15 g",
        note: "Cùng nhóm liều dimethomorph 50% WP. Luôn đối chiếu nhãn.",
      },
      phi: "Theo nhãn.",
      mixNotes: [
        "Không pha Insuran, Phytocide hoặc Eddy: trùng dimethomorph (FRAC 40).",
        "WP: hòa trước. Thường phối thuốc tiếp xúc khác nhóm.",
      ],
      tags: ["CAA", "Phytophthora", "dimethomorph"],
    },
    {
      id: "dantotsu",
      name: "Dantotsu 50WG",
      form: "WG",
      kind: "tru-sau",
      bio: false,
      ai: "Clothianidin 500 g/kg (50%)",
      group: "IRAC 4A",
      company: "Sumitomo",
      pack: "5 g",
      targets: "Rệp muỗi, kiến, bọ xít, rầy, bọ trĩ, rầy nâu — lưu dẫn mạnh, thấm sâu.",
      crops: "Theo nhãn. Cấm hành tây và rau gia vị — xem bộ Tra pha.",
      dose: {
        per16: "5 g",
        per1000: "10 g / 32 lít nước",
        note: "Bảng pha vườn: 10 g / 32 lít / 1000 m² (pha 1:3200, khoảng 1:1620–1:3205). Gói 5 g. Không nhầm với Dantotsu hạt rải (GR).",
      },
      phi: "7 ngày.",
      mixNotes: ["WG: rắc vào nước khuấy, đợi nở.", "Không pha Mospilan, Map Jono, Mikhada, Anvado, Thiamax hoặc Actara (cùng IRAC 4A)."],
      tags: ["neonicotinoid", "clothianidin", "rầy", "50wg", "dantotsu"],
    },
    {
      id: "viroval",
      name: "Viroval 50WP",
      form: "WP",
      kind: "tru-benh",
      bio: false,
      ai: "Iprodione 500 g/kg",
      group: "FRAC 2",
      company: "Phổ biến trên thị trường VN",
      targets: "Thối nhũn, đốm lá, thán thư, nấm đất trên cổ rễ — tiếp xúc / nội hấp cục bộ.",
      crops: "Theo nhãn. Cấm nhiều hành, xà lách, cải, đậu — xem bộ Tra pha.",
      dose: {
        per16: "Theo nhãn",
        note: "BTN trên nhãn Việt Nam = bột thấm nước (WP).",
      },
      phi: "Theo nhãn.",
      mixNotes: ["WP: hòa hồ đặc trước.", "Dễ kháng dicarboximide — không lặp liên tục."],
      tags: ["iprodione", "thối nhũn"],
    },
    {
      id: "rimon",
      name: "Rimon 10EC",
      form: "EC",
      kind: "tru-sau",
      bio: false,
      ai: "Novaluron 100 g/l",
      group: "IRAC 15",
      company: "ADAMA / phổ biến VN",
      targets: "Sâu tơ, sâu xanh, bọ cánh cứng — IGR, sâu không lột xác được.",
      crops: "Theo nhãn. Cấm nhiều hành, cải, cà tím, khoai lang — xem bộ Tra pha.",
      dose: {
        per16: "Theo nhãn",
        note: "Hiệu lực chậm hơn thuốc độc thần kinh. Phun khi sâu còn nhỏ.",
      },
      phi: "Theo nhãn.",
      mixNotes: ["EC: cho gần cuối.", "Không kỳ vọng diệt trưởng thành ngay."],
      tags: ["IGR", "novaluron", "sâu tơ"],
    },
    {
      id: "secsaigon",
      name: "Sec Saigon 10EC",
      form: "EC",
      kind: "tru-sau",
      bio: false,
      ai: "Cypermethrin 100 g/l",
      group: "IRAC 3A",
      company: "Nhiều nhà",
      targets: "Sâu cuốn lá, sâu xanh, rầy — cúc tổng hợp tiếp xúc.",
      crops: "Theo nhãn. Cấm hành tây, xà lách, bí ngô — xem bộ Tra pha.",
      dose: {
        per16: "Theo nhãn",
        note: "Cùng cypermethrin với NP-Cyrin Super. Độc ong, cá.",
      },
      phi: "Theo nhãn.",
      mixNotes: [
        "EC: cho gần cuối. Hạn chế pha 2 EC.",
        "Không pha NP-Cyrin Super (trùng cypermethrin) hoặc Map-Permethrin (IRAC 3A).",
      ],
      tags: ["cúc tổng hợp", "cypermethrin", "cyrin", "sec saigon"],
    },
    {
      id: "cyrin",
      name: "NP-Cyrin Super",
      form: "EC",
      kind: "tru-sau",
      bio: false,
      ai: "Cypermethrin (hàm lượng theo nhãn lô)",
      group: "IRAC 3A",
      company: "NP / phổ biến trên thị trường VN",
      targets: "Sâu cuốn lá, sâu xanh, rầy — cùng hoạt chất Sec Saigon 10EC.",
      crops: "Theo nhãn. Cùng cây cấm với Sec Saigon — xem bộ Tra pha.",
      dose: {
        per16: "Theo nhãn",
        note: "Tên chai 'Super' không có nghĩa liều giống Sec Saigon 10EC. Đọc % cypermethrin trên nhãn.",
      },
      phi: "Theo nhãn.",
      mixNotes: [
        "EC: cho gần cuối. Hạn chế pha 2 EC.",
        "Không pha Sec Saigon (trùng cypermethrin) hoặc Map-Permethrin (IRAC 3A).",
        "Độc ong, cá. Không phun khi hoa nở rộ.",
      ],
      tags: ["cúc tổng hợp", "cypermethrin", "cyrin", "np-cyrin"],
    },
    {
      id: "diazan",
      name: "DIAZAN 10H",
      form: "GR",
      kind: "tru-sau",
      bio: false,
      ai: "Diazinon 10%",
      group: "IRAC 1B",
      company: "Phổ biến trên thị trường VN",
      targets: "Sâu đất, tuyến trùng, côn trùng đất — hạt rải gốc.",
      crops: "Theo nhãn. Cấm nhiều hành, cải, khoai lang, mitsuba — xem trang thuốc.",
      dose: {
        per16: "Không pha bình phun",
        note: "Hạt rải (H/GR). Không hòa nước phun lá.",
      },
      phi: "Theo nhãn.",
      mixNotes: ["Không cho vào bình phun lá.", "Rải theo hàng/gốc đúng nhãn. Bảo hộ khi rải."],
      tags: ["hạt rải", "diazinon", "sâu đất"],
    },
    {
      id: "makeno",
      name: "Makeno 10GR",
      form: "GR",
      kind: "tru-sau",
      bio: false,
      ai: "Fosthiazate 10%",
      group: "IRAC 1B (lân hữu cơ — tuyến trùng)",
      company: "Phổ biến trên thị trường VN",
      targets: "Tuyến trùng, sâu đất — hạt rải gốc.",
      crops: "Theo nhãn. Cấm nhiều hành, cải, cà tím, đậu — xem trang thuốc.",
      dose: {
        per16: "Không pha bình phun",
        note: "Hạt rải (GR). Không hòa nước phun lá.",
      },
      phi: "Theo nhãn.",
      mixNotes: ["Không cho vào bình phun lá.", "Rải đất theo nhãn. Không trộn với thuốc phun."],
      tags: ["hạt rải", "fosthiazate", "tuyến trùng"],
    },
  ];

  const PRODUCT_AI = {
    dipel: ["bt"],
    secure: ["chlorfenapyr"],
    prevathon: ["chlorantraniliprole"],
    prevathon200: ["chlorantraniliprole"],
    benevia: ["cyantraniliprole"],
    permethrin: ["permethrin"],
    mospilan: ["acetamiprid"],
    jono: ["imidacloprid"],
    mikhada: ["imidacloprid"],
    anvado: ["imidacloprid"],
    amistar: ["azoxystrobin"],
    ranman: ["cyazofamid"],
    metaxyl: ["metalaxyl"],
    insuran: ["dimethomorph"],
    phytocide: ["dimethomorph"],
    eddy: ["dimethomorph", "cuprous_oxide"],
    kimono: ["boscalid"],
    coc: ["copper_oxychloride"],
    neem: ["azadirachtin"],
    acti: ["streptomyces"],
    thiamax: ["thiamethoxam"],
    actara: ["thiamethoxam"],
    kanaka: ["myclobutanil"],
    cylen: ["dimethomorph"],
    dantotsu: ["clothianidin"],
    viroval: ["iprodione"],
    rimon: ["novaluron"],
    secsaigon: ["cypermethrin"],
    cyrin: ["cypermethrin"],
    diazan: ["diazinon"],
    makeno: ["fosthiazate"],
  };

  /* Tỷ lệ pha loãng từ bảng vườn: ratio = hệ số gợi ý; upper = ngưỡng đậm (số nhỏ → nhiều thuốc); lower = ngưỡng nhạt (số lớn → ít thuốc). 1:N = 1 g hoặc ml thuốc trong N ml nước. */
  const DOSE_DILUTION = {
    dipel: { ratio: 800, upper: 267, lower: 5000, unit: "g" },
    secure: { ratio: 1500, upper: 595, lower: 2083, unit: "ml" },
    prevathon200: { ratio: 2647, upper: 2700, lower: 2600, unit: "ml" },
    benevia: { ratio: 625, upper: 625, lower: 625, unit: "ml" },
    permethrin: { ratio: 2000, upper: 1501, lower: 2500, unit: "ml" },
    dantotsu: { ratio: 3200, upper: 1620, lower: 3205, unit: "g" },
    mospilan: { ratio: 750, upper: 446, lower: 833, unit: "ml" },
    jono: { ratio: 10000, upper: 10000, lower: 10000, unit: "g" },
    thiamax: { ratio: 10000, upper: 10000, lower: 10000, unit: "g" },
    amistar: { ratio: 1500, upper: 1250, lower: 1666, unit: "ml" },
    ranman: { ratio: 900, upper: 900, lower: 950, unit: "ml" },
    metaxyl: { ratio: 900, upper: 842, lower: 1280, unit: "g" },
    insuran: { ratio: 500, upper: 277, lower: 5000, unit: "g" },
    phytocide: { ratio: 1000, upper: 1000, lower: 1000, unit: "g" },
    eddy: { ratio: 333, upper: 333, lower: 500, unit: "g" },
    kimono: { ratio: 2000, upper: 2000, lower: 2000, unit: "g" },
    coc: { ratio: 400, upper: 200, lower: 400, unit: "g" },
    neem: { ratio: 400, upper: 320, lower: 533, unit: "ml" },
    acti: { ratio: 1600, upper: 1600, lower: 1600, unit: "g" },
  };

  PRODUCTS.forEach((p) => {
    p.aiKeys = PRODUCT_AI[p.id] || [];
    if (DOSE_DILUTION[p.id]) p.dose.dilution = DOSE_DILUTION[p.id];
  });

  const KIND_LABEL = {
    "tru-sau": "Trừ sâu / rầy",
    "tru-benh": "Trừ bệnh",
  };

  const AI_LABEL = {
    petroleum_oil: "Dầu khoáng",
    myclobutanil: "Myclobutanil (Kanaka)",
    metalaxyl: "Metalaxyl (Metaxyl)",
    dimethomorph: "Dimethomorph (Cylen, Insuran, Phytocide, Eddy)",
    boscalid: "Boscalid (Kimono)",
    imidacloprid: "Imidacloprid (Map Jono, Mikhada, Anvado)",
    clothianidin: "Clothianidin (Dantotsu 50WG)",
    thiamethoxam: "Thiamethoxam (Thiamax, Actara)",
    iprodione: "Iprodione (Viroval)",
    permethrin: "Permethrin (Map-Permethrin)",
    cyazofamid: "Cyazofamid (Ranman)",
    lambda_cyhalothrin: "Cyhalothrin",
    azoxystrobin: "Azoxystrobin (Amistar)",
    acetamiprid: "Acetamiprid (Mospilan)",
    chlorfenapyr: "Chlorfenapyr (Secure)",
    novaluron: "Novaluron (Rimon)",
    diazinon: "Diazinon (Diazan 10H)",
    fosthiazate: "Fosthiazate (Makeno 10GR)",
    chlorantraniliprole: "Chlorantraniliprole (Prevathon 5SC, 200SC)",
    cyantraniliprole: "Cyantraniliprole (Benevia)",
    cypermethrin: "Cypermethrin (Sec Saigon, NP-Cyrin Super)",
  };

  const CROP_GROUPS = [
    { id: "hanh", name: "Hành, hẹ, gia vị", ja: "ねぎ・にら・香味野菜" },
    { id: "la", name: "Rau ăn lá", ja: "葉菜類" },
    { id: "cu", name: "Rau củ", ja: "根菜類" },
    { id: "qua", name: "Quả, đậu, khác", ja: "果菜・豆類・その他" },
  ];

  /* Cấm theo ô 使用不可 trên bảng chuẩn (4 sheet). Không suy diễn ô trống / 基準値なし. */
  const CROPS = [
    {
      id: "hanh-tay",
      name: "Hành tây",
      ja: "玉ねぎ",
      group: "hanh",
      bannedAis: [
        "petroleum_oil",
        "myclobutanil",
        "metalaxyl",
        "dimethomorph",
        "imidacloprid",
        "clothianidin",
        "thiamethoxam",
        "iprodione",
        "chlorfenapyr",
        "novaluron",
        "diazinon",
        "fosthiazate",
        "chlorantraniliprole",
        "cyantraniliprole",
        "cypermethrin",
      ],
    },
    {
      id: "he",
      name: "Hẹ",
      ja: "ニラ",
      group: "hanh",
      bannedAis: [
        "petroleum_oil",
        "dimethomorph",
        "permethrin",
        "imidacloprid",
        "chlorfenapyr",
        "novaluron",
        "diazinon",
        "fosthiazate",
      ],
    },
    {
      id: "hanh-huong",
      name: "Hành hương",
      ja: "わけぎ",
      group: "hanh",
      bannedAis: ["dimethomorph", "permethrin", "chlorfenapyr", "novaluron"],
    },
    {
      id: "hanh",
      name: "Hành",
      ja: "ネギ",
      group: "hanh",
      bannedAis: ["dimethomorph", "boscalid", "cyazofamid", "novaluron"],
    },
    {
      id: "mitsuba",
      name: "Rau cần ta (Mitsuba)",
      ja: "みつば",
      group: "hanh",
      bannedAis: [
        "myclobutanil",
        "metalaxyl",
        "dimethomorph",
        "permethrin",
        "thiamethoxam",
        "iprodione",
        "cyazofamid",
        "novaluron",
      ],
    },
    {
      id: "xa-lach",
      name: "Xà lách",
      ja: "レタス",
      group: "la",
      bannedAis: [
        "myclobutanil",
        "permethrin",
        "lambda_cyhalothrin",
        "iprodione",
        "chlorfenapyr",
        "novaluron",
        "diazinon",
        "chlorantraniliprole",
        "cypermethrin",
      ],
    },
    {
      id: "xa-lach-xoong",
      name: "Xà lách xoong",
      ja: "クレソン",
      group: "la",
      bannedAis: ["myclobutanil", "dimethomorph", "iprodione", "novaluron"],
    },
    {
      id: "bo-xoi",
      name: "Bó xôi",
      ja: "ほうれん草",
      group: "la",
      bannedAis: ["myclobutanil", "cyantraniliprole"],
    },
    {
      id: "cai-thia",
      name: "Cải thìa",
      ja: "チンゲン菜",
      group: "la",
      bannedAis: [
        "petroleum_oil",
        "myclobutanil",
        "dimethomorph",
        "permethrin",
        "iprodione",
        "chlorfenapyr",
        "novaluron",
        "diazinon",
        "fosthiazate",
      ],
    },
    {
      id: "cai-thao",
      name: "Cải thảo",
      ja: "白菜",
      group: "la",
      bannedAis: ["petroleum_oil", "myclobutanil", "iprodione"],
    },
    {
      id: "bap-cai",
      name: "Bắp cải",
      ja: "キャベツ",
      group: "la",
      bannedAis: ["petroleum_oil", "myclobutanil", "iprodione", "novaluron", "fosthiazate"],
    },
    {
      id: "cai-ngong",
      name: "Cải ngọt (Komatsuna)",
      ja: "小松菜",
      group: "la",
      bannedAis: ["novaluron"],
    },
    {
      id: "la-cu-cai",
      name: "Lá củ cải",
      ja: "葉大根",
      group: "la",
      bannedAis: ["petroleum_oil", "myclobutanil", "iprodione", "diazinon", "fosthiazate"],
    },
    {
      id: "rau-vn",
      name: "Rau bán ở Việt Nam",
      ja: "現地向け品種",
      group: "la",
      bannedAis: [],
    },
    {
      id: "ca-rot",
      name: "Cà rốt",
      ja: "ニンジン",
      group: "cu",
      bannedAis: ["petroleum_oil", "myclobutanil", "dimethomorph", "chlorantraniliprole", "novaluron"],
    },
    {
      id: "cu-cai",
      name: "Củ cải",
      ja: "大根",
      group: "cu",
      bannedAis: ["petroleum_oil", "myclobutanil", "iprodione", "diazinon", "fosthiazate"],
    },
    {
      id: "khoai-lang",
      name: "Khoai lang (Caiapo)",
      ja: "カイアポイモ",
      group: "cu",
      bannedAis: [
        "petroleum_oil",
        "myclobutanil",
        "metalaxyl",
        "dimethomorph",
        "iprodione",
        "fosthiazate",
        "cyantraniliprole",
        "novaluron",
      ],
    },
    {
      id: "bi-ngo",
      name: "Bí ngô / Bí ngòi",
      ja: "かぼちゃ",
      group: "qua",
      bannedAis: ["petroleum_oil", "thiamethoxam", "fosthiazate", "cyantraniliprole", "cypermethrin"],
    },
    {
      id: "dau-nhat",
      name: "Đậu Nhật / Đậu cô ve",
      ja: "インゲン",
      group: "qua",
      bannedAis: [
        "myclobutanil",
        "metalaxyl",
        "dimethomorph",
        "azoxystrobin",
        "iprodione",
        "cyazofamid",
        "novaluron",
      ],
    },
    {
      id: "rau-day",
      name: "Rau đay",
      ja: "モロヘイヤ",
      group: "qua",
      bannedAis: ["lambda_cyhalothrin", "imidacloprid", "chlorfenapyr", "fosthiazate"],
    },
    {
      id: "bap-ngot",
      name: "Bắp ngọt",
      ja: "スイートコーン",
      group: "qua",
      bannedAis: ["diazinon", "fosthiazate", "myclobutanil", "dimethomorph"],
    },
    {
      id: "ca-tim",
      name: "Cà tím",
      ja: "ナス",
      group: "qua",
      bannedAis: [
        "dimethomorph",
        "acetamiprid",
        "clothianidin",
        "thiamethoxam",
        "chlorfenapyr",
        "novaluron",
        "chlorantraniliprole",
      ],
    },
    {
      id: "gung",
      name: "Gừng",
      ja: "生姜",
      group: "qua",
      bannedAis: [],
    },
  ];

  const HARD_PAIRS = [
    {
      a: "coc",
      b: "*",
      level: "block",
      reason: "COC 85 (copper oxychloride) và Booc-đô được khuyến cáo phun riêng, khác một số đồng hydroxide.",
    },
    {
      a: "acti",
      b: "kind:tru-benh",
      level: "block",
      reason: "Streptomyces (Acti No Vate) bị diệt bởi thuốc trừ nấm/đồng/kháng sinh hóa học. Phun cách ly 5–7 ngày.",
    },
    {
      a: "dipel",
      b: "coc",
      level: "caution",
      reason: "Đồng kiềm có thể giảm Bt. Nếu vẫn dùng, phun ngay; tốt nhất tách buổi.",
    },
    {
      a: "dipel",
      b: "eddy",
      level: "caution",
      reason: "Eddy chứa đồng. Dipel + đồng: chỉ khi thử cốc đạt và phun ngay.",
    },
    {
      a: "acti",
      b: "dipel",
      level: "ok",
      reason: "Hai chế phẩm sinh học khác đối tượng; vẫn thử cốc và không để kiềm.",
    },
  ];

  const SAME_GROUP_RULES = [
    {
      ids: ["prevathon", "prevathon200", "benevia"],
      group: "IRAC 28 (diamide)",
      level: "block",
      reason: "Prevathon 5SC, Dupont Prevathon 200SC và Benevia cùng nhóm ryanodine (28). Chọn một loại.",
    },
    {
      ids: ["mospilan", "jono", "mikhada", "anvado", "thiamax", "actara", "dantotsu"],
      group: "IRAC 4A (neonicotinoid)",
      level: "block",
      reason: "Mospilan, Map Jono / Mikhada / Anvado, Thiamax / Actara và Dantotsu cùng nhóm 4A. Chọn một chai; luân phiên nhóm khác.",
    },
    {
      ids: ["insuran", "phytocide", "eddy", "cylen"],
      group: "FRAC 40 (dimethomorph)",
      level: "block",
      reason: "Trùng dimethomorph. Eddy đã chứa 12% dimethomorph — không cộng thêm Insuran/Phytocide/Cylen.",
    },
    {
      ids: ["permethrin", "secsaigon", "cyrin"],
      group: "IRAC 3A (cúc tổng hợp)",
      level: "block",
      reason: "Map-Permethrin, Sec Saigon và NP-Cyrin Super cùng nhóm 3A. Chọn một loại; độc ong.",
    },
  ];

  const SOURCES = [
    {
      title: "CropLife International — Catalogue of pesticide formulation types (Technical Monograph No. 2)",
      url: "https://croplife.org/wp-content/uploads/2023/03/Technical-Monograph-N2-8th-edition_2022_final.pdf",
      use: "Mã dạng chế phẩm WP, WG, EC, SC, OD, SP, SL… chuẩn quốc tế (FAO viện dẫn).",
    },
    {
      title: "FAO Pesticide Registration Toolkit — Type of formulation and code",
      url: "https://www.fao.org/pesticide-registration-toolkit/registration-tools/data-requirements-and-testing-guidelines/study-detail/en/c/1186059/",
      use: "Yêu cầu ghi dạng chế phẩm theo mã CropLife.",
    },
    {
      title: "Syngenta — WALES mixing order",
      url: "https://www.syngenta.ca/agronomy/wales-mixing-order",
      use: "Thứ tự: Water → WP → WDG → SC → EC → SL.",
    },
    {
      title: "Virginia Tech Extension — Spray tank mixing (WALES/DALES)",
      url: "https://pubs.ext.vt.edu/BSE/bse-351/bse-351.html",
      use: "Nguyên tắc tank-mix và thử tương hợp.",
    },
    {
      title: "The Voluntary Initiative (UK) — Tank Mix Guide 2026",
      url: "https://voluntaryinitiative.org.uk/media/bppivysf/the-vi-and-tank-mix-guide-2026_v4_tm_only.pdf",
      use: "Thứ tự chi tiết WG/WP → SC → CS → SE → EW → EC → OD → SL.",
    },
    {
      title: "Sumitomo / Valent — DiPel mixing guidelines",
      url: "https://www.sumitomobiorational.com/wp-content/uploads/2022/06/dipel-mixing-guidelines-technical-bulletin-ag-5423.pdf",
      use: "pH 4,5–8, thử cốc, phun trong 24 giờ; đồng phải phun ngay.",
    },
    {
      title: "Danh mục thuốc BVTV Việt Nam (danhmuc.thuocbvtv.com)",
      url: "https://danhmuc.thuocbvtv.com/",
      use: "Hoạt chất, cây trồng, liều ha của sản phẩm đăng ký (Dipel, Benevia, Amistar, Eddy…).",
    },
    {
      title: "Thông tư danh mục thuốc BVTV (Bộ NN&MT)",
      url: "https://luatvietnam.vn/nong-nghiep/thong-tu-28-2026-tt-bnnmt-danh-muc-thuoc-bao-ve-thuc-vat-tai-viet-nam-439351-d1.html",
      use: "Ranman 10SC (cyazofamid) và copper oxychloride trong danh mục cho phép.",
    },
    {
      title: "Nguyên tắc phối trộn BVTV (tài liệu kỹ thuật trong nước)",
      url: "https://sopphumy.com.vn/huong-dan-mot-so-nguyen-tac-phoi-tron-thuoc-bvtv.html",
      use: "WP/WG trước; SC → OD → EC; COC 85/Booc-đô phun riêng; carbamate kim loại kỵ kháng sinh.",
    },
    {
      title: "Map Pacific — Map Jono 700WP, Map Permethrin 50EC",
      url: "https://www.mappacific.com/en/product/map-jono-700wp/",
      use: "Liều imidacloprid 700 g/kg và permethrin theo nhãn hãng.",
    },
    {
      title: "Hợp Trí — Thiamax 25WG, Eddy 72WP",
      url: "https://hoptrisummit.com/san-pham/thuoc-bao-ve-thuc-vat/thuoc-tru-sau/thiamax-25wg",
      use: "Thiamethoxam 4 g/16 lít; Eddy cuprous oxide + dimethomorph.",
    },
    {
      title: "IRAC Mode of Action Classification",
      url: "https://irac-online.org/mode-of-action/",
      use: "Nhóm trừ sâu 3A, 4A, 11A, 13, 28 — không chồng cùng nhóm.",
    },
    {
      title: "FRAC Code List",
      url: "https://www.frac.info/",
      use: "Nhóm trừ bệnh 4, 7, 11, 21, 40, M01, M05 — luân phiên chống kháng.",
    },
  ];

  const formByCode = Object.fromEntries(FORMS.map((f) => [f.code, f]));
  const productById = Object.fromEntries(PRODUCTS.map((p) => [p.id, p]));
  const cropById = Object.fromEntries(CROPS.map((c) => [c.id, c]));

  function productBannedOnCrop(product, crop) {
    if (!product || !crop) return false;
    const keys = product.aiKeys || [];
    return keys.some((k) => crop.bannedAis.includes(k));
  }

  function bannedCropsForProduct(product) {
    if (!product) return [];
    return CROPS.filter((c) => productBannedOnCrop(product, c));
  }

  return {
    FORMS,
    MIX_ORDER,
    PRODUCTS,
    KIND_LABEL,
    AI_LABEL,
    CROP_GROUPS,
    CROPS,
    HARD_PAIRS,
    SAME_GROUP_RULES,
    SOURCES,
    formByCode,
    productById,
    cropById,
    productBannedOnCrop,
    bannedCropsForProduct,
  };
})();
